<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SspTalks\Controller\TalksController' => __DIR__ . '/src/SspTalks/Controller/TalksController.php',
    'SspTalks\Module'                       => __DIR__ . '/Module.php',
    'SspTalksTest\SampleTest'               => __DIR__ . '/tests/SspTalks/SampleTest.php',
    'SspTalksTest\Framework\TestCase'       => __DIR__ . '/tests/SspTalks/Framework/TestCase.php',
);
