<div class="page-header">
    <h1>Keynotes</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        Below is a full listing of the keynotes to be presented during the conference from February 3rd to 4th.<br /><br />
    </p>

    <div style="padding-left: 30px;">

        <div id="accidental-professional" style="text-align: justify;">
            <hr />

            <h2>Accidental Professional</h2>

            <a href="/speakers#adam-culp" title="Speaker: adam-culp">Adam Culp</a>
            <div class="tag large keynote">Keynote</div>

            <br /><br />

            Humans learn most effectively through pain, like being shocked by a power outlet or touching a hot iron. The same reaction can be found in technology, but how can we attribute this to programming while minimizing the most painful mistakes? Adam Culp will share some life experiences that contributed to his ongoing journey to become a professional developer, and highlight techniques used to reduce the pain and still reap the benefits. This keynote encourages attendees to aspire to achieve more in their lives.<br /><br />
        </div>
        
        <div id="a-world-without-php" style="text-align: justify;">
            <hr />

            <h2>A World Without PHP</h2>

            <a href="/speakers#ben-marks" title="Speaker: Ben Marks">Ben Marks</a>
            <div class="tag large keynote">Keynote</div>

            <br /><br />

            Imagine a world in which your career, the careers of your friends and coworkers, and the businesses and industries built on PHP vanished overnight, or never existed at all. No Facebook. No Wordpress. Billions of dollars in online commerce, all gone. Flickr, Tumblr, MailChimp: poof!<br /><br />

            This talk presents a dystopian world in which we are stuck updating each other via SMS or (gasp!) MySpace, reading content on corporate portals, and buying everything from just a handful of online marketplaces.<br /><br />
        </div>

        <div id="life-badges" style="text-align: justify;">
            <hr />

            <h2>Life Badges</h2>

            <a href="/speakers#cal-evans" title="Speaker: Cal Evans">Cal Evans</a>
            <div class="tag large keynote">Keynote</div>

            <br /><br />

            Have you ever looked at a projects README.md and the first two to three lines are filled up with little graphics telling you the various stats of the project? The "badges" have become popular because they are a quick way for developers to communicate information about the project.<br /><br />

            I want badges for my life. When people look at my life's README.md, what badges do I want them to see? What badges do they really see? What can I do to control this?<br /><br />

            Join me as we jog through the list of Life Badges I want people to see on my life's repo. Along the way, we'll pause briefly to examine what each badge means, and what color is appropriate. As we examinemy README.md, you may be surprised at what you learn about me...and about your own life badges.<br /><br />
        </div>

        <div id="the-new-revolution" style="text-align: justify;">
            <hr />

            <h2>The New Revolution</h2>

            <a href="/speakers#samantha-quinones" title="Speaker: Samantha Quiñones">Samantha Quiñones</a>
            <div class="tag large keynote">Keynote</div>

            <br /><br />

            In 1969, researchers at Stanford and UCLA collaborated to transmit the first message over what would become the Internet. In just five decades, the repercussions of that moment have echoed through every atom of society. The world is evolving at a pace unprecedented in human history as we use technology to change how we think, learn, communicate, and even how we understand ourselves. Let’s take an inside look at how the fusion of media and technology is reinventing human interaction and the role that we, as engineers and technologists, must play in this important process.<br /><br />
        </div>

        <div id="using-open-source-for-fun-and-profit" style="text-align: justify;">
            <hr />

            <h2>Using Open Source for Fun and Profit</h2>

            <a href="/speakers#gary-hockin" title="Speaker: Gary Hockin">Gary Hockin</a>
            <div class="tag large keynote">Keynote</div>

            <br /><br />

            10 years ago I was a lonely developer sitting in a small room quietly turning out code between 9am and 5pm, Monday to Friday. Fast-forward to now and you'll see me standing in front of audiences all around the world talking to developers about numerous topics."Why are you bragging like that at me?" I hear you ask. Because it could happen to you too.<br /><br />

            The question I always ask myself is "How the hell did that happen?!?!".<br /><br />

            The truth is that the only reason I've managed to advance my career so far in a decade is because of the people that make up the communities of open source projects. Not only do open source projects save you time and money, but the friendships and support groups that can be made within these communities is, frankly, staggering.<br /><br />

            Join me as I chart my journey from wage slave to conference speaker, and look at how you can leverage the power of open source to make real friends, real money, and real happiness.<br /><br />
        </div>

    </div>
    <hr />
</div>