<div class="page-header">
    <h1>Keynotes</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        Below is a full listing of the keynotes to be presented during the conference from February 3rd to 4th.<br /><br />
    </p>

    <div style="padding-left: 30px;">

        <div id="talk_tag" style="text-align: justify;">
            <hr />

            <h2>keynote_title</h2>

            <a href="/speakers#speaker_tag" title="Speaker: speaker_name">speaker_name</a>
            <div class="tag large keynote">Keynote</div>

            <br /><br />

            keynote_abstract<br /><br />
        </div>

        <div id="talk_tag" style="text-align: justify;">
            <hr />

            <h2>keynote_title</h2>

            <a href="/speakers#speaker_tag" title="Speaker: speaker_name">speaker_name</a>
            <div class="tag large keynote">Keynote</div>

            <br /><br />

            keynote_abstract<br /><br />
        </div>

        <div id="talk_tag" style="text-align: justify;">
            <hr />

            <h2>keynote_title</h2>

            <a href="/speakers#speaker_tag" title="Speaker: speaker_name">speaker_name</a>
            <div class="tag large keynote">Keynote</div>

            <br /><br />

            keynote_abstract<br /><br />
        </div>

        <div id="talk_tag" style="text-align: justify;">
            <hr />

            <h2>keynote_title</h2>

            <a href="/speakers#speaker_tag" title="Speaker: speaker_name">speaker_name</a>
            <div class="tag large keynote">Keynote</div>

            <br /><br />

            keynote_abstract<br /><br />
        </div>

        <div id="talk_tag" style="text-align: justify;">
            <hr />

            <h2>keynote_title</h2>

            <a href="/speakers#speaker_tag" title="Speaker: speaker_name">speaker_name</a>
            <div class="tag large keynote">Keynote</div>

            <br /><br />

            keynote_abstract<br /><br />
        </div>

    </div>
    <hr />
</div>