<div class="page-header">
    <h1>Schedule & Layout</h1>
</div>
<div id="block-mine">
    <div id="schedule">

        <!-- Speakers, Talks, and Tutorials links -->
        
        <h3>Related Links:</h3>
        <div style="text-align: center">
            <a class="btn btn-large btn-info" href="/speakers" title="Full Speakers List">Full Speakers List</a>&nbsp;&nbsp;
            <a class="btn btn-large btn-info" href="/talks" title="Full Talks List">Full Talks List</a>&nbsp;&nbsp;
            <a class="btn btn-large btn-info" href="/tutorials" title="Full Tutorials List">Full Tutorials List</a><br /><br />
        </div>
    
        <!-- Overall details of side rooms -->
        
        <table>
            <tbody>
            <tr class="bottomline">
                <th class="span12" colspan="4">Venue room assignments for the conference</th>
            </tr>
            <tr class="bottomline">
                <td class="span3"><strong>Grand Ballroom</strong></td>
                <td>Keynotes and sessions throughout each day</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key Biscayne #1</strong></td>
                <td>Sessions throughout each day</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key Biscayne #2</strong></td>
                <td>Sessions throughout each day</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key West Ballroom</strong></td>
                <td>Sessions throughout each day</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key Largo #1</strong></td>
                <td>Registration and Support</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key Largo #2 and #3</strong></td>
                <td>Sponsor interaction area and coffee/snacks each day</td>
            </tr>
            <tr>
                <td ><strong>Key Largo #4</strong></td>
                <td>Wifi lounge and Uncon track each day</td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- hotel layout image -->
        
        <img src="/img/hotel_layout.png" alt="Conference Layout Image" />
        <hr />

        <!-- Pre-Conference -->

        <!-- <div class="f_legend"><div class="tag small magento" title="Magento">M</div>= Magento &nbsp; <div class="tag small laravel" title="Laravel">L</div>= Laravel &nbsp; <div class="tag small wordpress" title="WordPress">W</div>= WordPress &nbsp; <div class="tag small drupal" title="Drupal">D</div>= Drupal &nbsp; <div class="tag small joomla" title="Joomla!">J</div>= Joomla! &nbsp; <div class="tag small zendframework" title="Zend Framework">Z</div>= Zend Framework &nbsp; <div class="tag small symfony" title="Symfony">S</div>= Symfony &nbsp; <div class="tag small cakephp" title="CakePHP">C</div>= CakePHP &nbsp; </div> -->

        <table>
            <tbody>
            <tr>
                <th class="span12" colspan="5">Wednesday Feb. 1st, 2017</th>
            </tr>
            <tr>
                <td class="span2">17:30 - 19:30</td>
                <td class="keyrow" colspan="4"><strong>Happy Hour</strong> Atrium bar</td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- Tutorial Day -->
        
        <table>
            <tbody>
            <tr>
                <th class="span12"  colspan="5">Tutorial Day - Thursday Feb. 2nd, 2017</th>
            </tr>
            <tr class="bottomline">
                <td>Room</td>
                <td>Grand Ballrooom</td>
                <td>Key Biscayne #1 (front)</td>
                <td>Key Biscayne #2 (rear)</td>
                <td>Key West Ballroom</td>
            </tr>
            <tr class="bottomline">
                <td class="span2">8:00 - 9:00</td>
                <td class="keyrow" colspan="4"><strong>Tutorial Registration Opens</strong> in Key Largo #1</td>
            </tr>
            <tr class="bottomline">
                <td>9:00 - 12:00</td>
                <td class="span3"><a title="Tutorial: tutorial_title" href="/tutorials#tutorial_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span3"><a title="Tutorial: tutorial_title" href="/tutorials#tutorial_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span3"><a title="Tutorial: tutorial_title" href="/tutorials#tutorial_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span3"><a title="Tutorial: tutorial_title" href="/tutorials#tutorial_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>12:00 - 13:00</td>
                <td class="lunch" colspan="4">Lunch</td>
            </tr>
            <tr class="bottomline">
                <td>13:00 - 16:00</td>
                <td class="span3"><a title="Tutorial: tutorial_title" href="/tutorials#tutorial_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span3"><a title="Tutorial: tutorial_title" href="/tutorials#tutorial_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span3"><a title="Tutorial: tutorial_title" href="/tutorials#tutorial_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span3"><a title="Tutorial: tutorial_title" href="/tutorials#tutorial_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
            </tr>
            <tr>
                <td>17:30 - 19:30</td>
                <td class="keyrow" colspan="4"><strong>Happy Hour</strong> Atrium bar</td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- Day #1 -->
        
        <table>
            <tbody>
            <tr>
                <th class="span12" colspan="5">Day 1 - Friday Feb. 3rd, 2017</th>
            </tr>
            <tr class="bottomline">
                <td>Room</td>
                <td>Grand Ballrooom</td>
                <td>Key Biscayne #1 (front)</td>
                <td>Key Biscayne #2 (rear)</td>
                <td>Key West Ballroom</td>
            </tr>
            <tr class="bottomline">
                <td class="span2">8:00 - 9:00</td>
                <td colspan="4"><strong>Conference Registration Opens</strong> in Key Largo #1</td>
            </tr>
            <tr class="bottomline">
                <td>9:00 - 10:00</td>
                <td class="keyrow" colspan="4">Opening Keynote - in Grand Ballroom<br />
                    "TBA"<br />
                    <a title="Speaker: Ben Marks" href="/speakers#ben-marks">Ben Marks</a></td>
            </tr>
            <tr class="bottomline">
                <td>10:15 - 11:15</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>11:30 - 12:30</td>
                <<td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>12:30 - 13:30</td>
                <td class="lunch" colspan="4">Lunch</td>
            </tr>
            <tr class="bottomline">
                <td>13:30 - 14:30</td>
                <td class="keyrow" colspan="4">Lunch Keynote - in Grand Ballroom<br />
                    "TBA"<br />
                    <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a></td>
            </tr>
            <tr class="bottomline">
                <td>14:45 - 15:45</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>16:00 - 17:00</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>17:15 - 18:15</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
            </tr>
            <tr>
                <td>Evening</td>
                <td class="keyrow" colspan="4">
                    <strong>Happy Hour</strong> from 18:30 - 19:30 featuring <strong>"What's it?" Game</strong> Grand Ballroom<br />
                    <strong>Hackathon</strong> 19:00 - ???
                </td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- Day #2 -->

        <table>
            <tbody>
            <tr>
                <th class="span12" colspan="5">Day 2 - Saturday Feb. 4th, 2017</th>
            </tr>
            <tr class="bottomline">
                <td>Room</td>
                <td>Grand Ballrooom</td>
                <td>Key Biscayne #1 (front)</td>
                <td>Key Biscayne #2 (rear)</td>
                <td>Key West Ballroom</td>
            </tr>
            <tr class="bottomline">
                <td class="span2">9:00 - 10:00</td>
                <td class="keyrow" colspan="4">Day 2 Opening Keynote - in Grand Ballroom<br />
                    "TBA"<br />
                    <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a></td>
            </tr>
            <tr class="bottomline">
                <td>10:15 - 11:15</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>11:30 - 12:30</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>12:30 - 13:30</td>
                <td class="lunch" colspan="4">Lunch</td>
            </tr>
            <tr class="bottomline">
                <td>13:30 - 14:30</td>
                <td class="keyrow" colspan="4">Day 2 Lunch Keynote - in Grand Ballroom<br />
                    "TBA"<br />
                    <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a></td>
            </tr>
            <tr class="bottomline">
                <td>14:45 - 15:45</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>16:00 - 17:00</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>17:15 - 18:15</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
                <td class="span4"><a title="Talk: talk_title" href="/talks#talk_tag"><strong>TBD</strong></a><br />
                    - <a title="Speaker: speaker_name" href="/speakers#speaker_tag">TBD</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>18:15 - 19:15</td>
                <td class="keyrow" colspan="4"><strong>Closing Keynote - in Grand Ballroom</strong><br />
                    "TBA"<br />
                    <a title="Speaker: Cal Evans" href="/speakers#cal-evans">Cal Evans</a></td>
            </tr>
            <tr>
                <td>19:15 - 19:45</td>
                <td class="keyrow" colspan="4"><strong>Thank you & Prizes</strong><br />
                    Adam Culp</td>
            </tr>
            </tbody>
        </table>
        <hr />
    </div>

</div>