<div class="page-header">
    <h1>Schedule & Layout</h1>
</div>
<div id="block-mine">
    <div id="schedule">

        <!-- Speakers, Talks, and Tutorials links -->
        
        <h3>Related Links:</h3>
        <div style="text-align: center">
            <a class="btn btn-large btn-info" href="/speakers" title="Full Speakers List">Full Speakers List</a>&nbsp;&nbsp;
            <a class="btn btn-large btn-info" href="/talks" title="Full Talks List">Full Talks List</a>&nbsp;&nbsp;
            <a class="btn btn-large btn-info" href="/tutorials" title="Full Tutorials List">Full Tutorials List</a><br /><br />
        </div>
    
        <!-- Overall details of side rooms -->
        
        <table>
            <tbody>
            <tr class="bottomline">
                <th class="span12" colspan="4">Venue room assignments for the conference</th>
            </tr>
            <tr class="bottomline">
                <td class="span3"><strong>Grand Ballroom</strong></td>
                <td>Keynotes and sessions throughout each day</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key Biscayne #1</strong></td>
                <td>Sessions throughout each day</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key Biscayne #2</strong></td>
                <td>Sessions throughout each day</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key Largo #1</strong></td>
                <td>Registration and Support</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key Largo #2 and #3</strong></td>
                <td>Sponsor interaction area and coffee/snacks each day</td>
            </tr>
            <tr>
                <td ><strong>Key Largo #4</strong></td>
                <td>Wifi lounge and Uncon track each day</td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- hotel layout image -->
        
        <img src="/img/hotel_layout.png" alt="Conference Layout Image" />
        <hr />

        <!-- Pre-Conference -->

        <!-- <div class="f_legend"><div class="tag small magento" title="Magento">M</div>= Magento &nbsp; <div class="tag small laravel" title="Laravel">L</div>= Laravel &nbsp; <div class="tag small wordpress" title="WordPress">W</div>= WordPress &nbsp; <div class="tag small drupal" title="Drupal">D</div>= Drupal &nbsp; <div class="tag small joomla" title="Joomla!">J</div>= Joomla! &nbsp; <div class="tag small zendframework" title="Zend Framework">Z</div>= Zend Framework &nbsp; <div class="tag small symfony" title="Symfony">S</div>= Symfony &nbsp; <div class="tag small cakephp" title="CakePHP">C</div>= CakePHP &nbsp; </div> -->

        <table>
            <tbody>
            <tr>
                <th class="span12" colspan="5">Wednesday Feb. 3rd, 2016</th>
            </tr>
            <tr>
                <td class="span2">17:30 - 19:30</td>
                <td class="keyrow" colspan="4"><strong>Happy Hour</strong> Atrium bar</td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- Tutorial Day -->
        
        <table>
            <tbody>
            <tr>
                <th class="span12"  colspan="5">Tutorial Day - Thursday Feb. 4th, 2016</th>
            </tr>
            <tr class="bottomline">
                <td>Room</td>
                <td>Grand Ballrooom</td>
                <td>Key Biscayne #1 (front)</td>
                <td>Key Biscayne #2 (rear)</td>
                <td>Key West Ballroom</td>
            </tr>
            <tr class="bottomline">
                <td class="span2">8:00 - 9:00</td>
                <td class="keyrow" colspan="4"><strong>Tutorial Registration Opens</strong> in Key Largo #1</td>
            </tr>
            <tr class="bottomline">
                <td>9:00 - 12:00</td>
                <td class="span3"><a title="Tutorial: Test, Create, Secure, Repeat" href="/tutorials#test-create-secure-repeat"><strong>Test, Create, Secure, Repeat</strong></a><br />
                    - <a title="Speaker: Michelangelo van Dam" href="/speakers#michelangelo-van-dam">Michelangelo van Dam</a> -</td>
                <td class="span3"><a title="Tutorial: Adventures in Laravel 5" href="/tutorials#adventures-in-laravel-5"><strong>Adventures in Laravel 5</strong></a><br />
                    - <a title="Speaker: Joe Ferguson" href="/speakers#joe-ferguson">Joe Ferguson</a> -</td>
                <td class="span3"><a title="Tutorial: Docker for Developers" href="/tutorials#docker-for-developers"><strong>Docker for Developers</strong></a><br />
                    - <a title="Speaker: Chris Tankersley" href="/speakers#chris-tankersley">Chris Tankersley</a> -</td>
                <td class="span3"><a title="Tutorial: Become an Open Source Contributor" href="/tutorials#become-an-open-source-contributor"><strong>Become an Open Source Contributor</strong></a><br />
                    - <a title="Speaker: Beth Tucker Long" href="/speakers#beth-tucker-long">Beth Tucker Long</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>12:00 - 13:00</td>
                <td class="lunch" colspan="4">Lunch</td>
            </tr>
            <tr class="bottomline">
                <td>13:00 - 16:00</td>
                <td class="span3"><a title="Tutorial: ZF2 Done Properly" href="/tutorials#zf2-done-properly"><strong>ZF2 Done Properly</strong></a><br />
                    - <a title="Speaker: Gary Hockin" href="/speakers#gary-hockin">Gary Hockin</a> -</td>
                <td class="span3"><a title="Tutorial: Manage Your Content with Elasticsearch" href="/tutorials#manage-your-content-with-elasticsearch"><strong>Manage Your Content with Elasticsearch</strong></a><br />
                    - <a title="Speaker: Samantha Quiñones" href="/speakers#samantha-quinones">Samantha Quiñones</a> -</td>
                <td class="span3"><a title="Tutorial: Demystifying Object-Oriented Programming" href="/tutorials#demystifying-object-oriented-programming"><strong>Demystifying Object-Oriented Programming</strong></a><br />
                    - <a title="Speaker: Alena Holligan" href="/speakers#alena-holligan">Alena Holligan</a> -</td>
                <td class="span3"><a title="Tutorial: Magento 2 Modules are Easy!" href="/tutorials#magento-2-modules-are-easy"><strong>Magento 2 Modules are Easy!</strong></a><br />
                    - <a title="Speaker: Ben Marks" href="/speakers#ben-marks">Ben Marks</a> -</td>
            </tr>
            <tr>
                <td>17:30 - 19:30</td>
                <td class="keyrow" colspan="4"><strong>Happy Hour</strong> Atrium bar</td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- Day #1 -->
        
        <table>
            <tbody>
            <tr>
                <th class="span12" colspan="5">Day 1 - Friday Feb. 5th, 2016</th>
            </tr>
            <tr class="bottomline">
                <td>Room</td>
                <td>Grand Ballrooom</td>
                <td>Key Biscayne #1 (front)</td>
                <td>Key Biscayne #2 (rear)</td>
                <td>Key West Ballroom</td>
            </tr>
            <tr class="bottomline">
                <td class="span2">8:00 - 9:00</td>
                <td colspan="4"><strong>Conference Registration Opens</strong> in Key Largo #1</td>
            </tr>
            <tr class="bottomline">
                <td>9:00 - 10:00</td>
                <td class="keyrow" colspan="4">Opening Keynote - in Grand Ballroom<br />
                    "TBA"<br />
                    <a title="Speaker: Josh Holmes" href="/speakers#josh-holmes">Josh Holmes</a></td>
            </tr>
            <tr class="bottomline">
                <td>10:15 - 11:15</td>
                <td class="span4"><a title="Talk: Web Security and You" href="/talks#talkurl"><strong>Web Security and You</strong></a><br />
                    - <a title="Speaker: Eli White" href="/speakers#speakerurl">Eli White</a> -</td>
                <td class="span4"><a title="Talk: MySQL Server Performance Tuning 101" href="/talks#talkurl"><strong>MySQL Server Performance Tuning 101</strong></a><br />
                    - <a title="Speaker: Ligaya Turmelle" href="/speakers#speakerurl">Ligaya Turmelle</a> -</td>
                <td class="span4"><a title="Talk: Symfony Guard Authentication: Fun with API Token, Social Login, JWT and more" href="/talks#talkurl"><strong>Symfony Guard Authentication: Fun with API Token, Social Login, JWT and more</strong></a><br />
                    - <a title="Speaker: Ryan Weaver" href="/speakers#speakerurl">Ryan Weaver</a> -</td>
                <td class="span4"><a title="Talk: Feature Flags are Flawed: Let's Make Them Better" href="/talks#talkurl"><strong>Feature Flags are Flawed: Let's Make Them Better</strong></a><br />
                    - <a title="Speaker: Stephen Young" href="/speakers#speakerurl">Stephen Young</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>11:30 - 12:30</td>
                <td class="span4"><a title="Talk: Navigating Your Git Repository" href="/talks#talkurl"><strong>Navigating Your Git Repository</strong></a><br />
                    - <a title="Speaker: Gemma Anible" href="/speakers#speakerurl">Gemma Anible</a> -</td>
                <td class="span4"><a title="Talk: The Pattern to Design Patterns" href="/talks#talkurl"><strong>The Pattern to Design Patterns</strong></a><br />
                    - <a title="Speaker: Chris Russell" href="/speakers#speakerurl">Chris Russell</a> -</td>
                <td class="span4"><a title="Talk: PCI Compliance for PHP in the Hipster Age" href="/talks#talkurl"><strong>PCI Compliance for PHP in the Hipster Age</strong></a><br />
                    - <a title="Speaker: Phillip Jackson" href="/speakers#speakerurl">Phillip Jackson</a> -</td>
                <td class="span4"><a title="Talk: HTTP/2 The (not so) new Language of the Web" href="/talks#talkurl"><strong>HTTP/2 The (not so) new Language of the Web</strong></a><br />
                    - <a title="Speaker: Adrian Cardenas" href="/speakers#speakerurl">Adrian Cardenas</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>12:30 - 13:30</td>
                <td class="lunch" colspan="4">Lunch</td>
            </tr>
            <tr class="bottomline">
                <td>13:30 - 14:30</td>
                <td class="keyrow" colspan="4">Lunch Keynote - in Grand Ballroom<br />
                    "TBA"<br />
                    <a title="Speaker: Stephanie Evans" href="/speakers#stephanie-evans">Stephanie Evans</a></td>
            </tr>
            <tr class="bottomline">
                <td>14:45 - 15:45</td>
                <td class="span4"><a title="Talk: Give Me a REST!" href="/talks#talkurl"><strong>Give Me a REST!</strong></a><br />
                    - <a title="Speaker: Amanda Folson" href="/speakers#speakerurl">Amanda Folson</a> -</td>
                <td class="span4"><a title="Talk: Don't be the last to know!  Strategies &amp; Tactics for Monitoring Your System and Services." href="/talks#talkurl"><strong>Don't be the last to know!  Strategies &amp; Tactics for Monitoring Your System and Services.</strong></a><br />
                    - <a title="Speaker: Elisa Towbis" href="/speakers#speakerurl">Elisa Towbis</a> -</td>
                <td class="span4"><a title="Talk: Introduction to Graph Databases with Neo4j" href="/talks#talkurl"><strong>Introduction to Graph Databases with Neo4j</strong></a><br />
                    - <a title="Speaker: Michael Moussa" href="/speakers#speakerurl">Michael Moussa</a> -</td>
                <td class="span4"><a title="Talk:  Be a Bold Coder" href="/talks#talkurl"><strong> Be a Bold Coder</strong></a><br />
                    - <a title="Speaker: Beth Tucker Long" href="/speakers#speakerurl">Beth Tucker Long</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>16:00 - 17:00</td>
                <td class="span4"><a title="Talk: Step Into Debugging" href="/talks#talkurl"><strong>Step Into Debugging</strong></a><br />
                    - <a title="Speaker: Gary Hockin" href="/speakers#speakerurl">Gary Hockin</a> -</td>
                <td class="span4"><a title="Talk: Become a RUM runner!" href="/talks#talkurl"><strong>Become a RUM runner!</strong></a><br />
                    - <a title="Speaker: Vesna Kovach" href="/speakers#speakerurl">Vesna Kovach</a> -</td>
                <td class="span4"><a title="Talk: PHP Identity and Data Security" href="/talks#talkurl"><strong>PHP Identity and Data Security</strong></a><br />
                    - <a title="Speaker: Jonathan LeBlanc" href="/speakers#speakerurl">Jonathan LeBlanc</a> -</td>
                <td class="span4"><a title="Talk: APIs to your brain" href="/talks#talkurl"><strong>APIs to your brain</strong></a><br />
                    - <a title="Speaker: Ibis Arrastia" href="/speakers#speakerurl">Ibis Arrastia</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>17:15 - 18:15</td>
                <td class="span4"><a title="Talk: Applying the 4 Rules of Simple Design" href="/talks#talkurl"><strong>Applying the 4 Rules of Simple Design</strong></a><br />
                    - <a title="Speaker: Adam Wathan" href="/speakers#speakerurl">Adam Wathan</a> -</td>
                <td class="span4"><a title="Talk: Containers and Docker for the PHP developer" href="/talks#talkurl"><strong>Containers and Docker for the PHP developer</strong></a><br />
                    - <a title="Speaker: Robert McFrazier" href="/speakers#speakerurl">Robert McFrazier</a> -</td>
                <td class="span4"><a title="Talk: Behat: Beyond the Basics" href="/talks#talkurl"><strong>Behat: Beyond the Basics</strong></a><br />
                    - <a title="Speaker: Jessica Mauerhan" href="/speakers#speakerurl">Jessica Mauerhan</a> -</td>
                <td class="span4"><a title="Talk: Magento at 2" href="/talks#talkurl"><strong>Magento at 2</strong></a><br />
                    - <a title="Speaker: Ben Marks" href="/speakers#speakerurl">Ben Marks</a> -</td>
            </tr>
            <tr>
                <td>Evening</td>
                <td class="keyrow" colspan="4">
                    <strong>Happy Hour</strong> from 18:30 - 19:30 featuring <strong>"What's it?" Game</strong> Grand Ballroom<br />
                    <strong>Hackathon</strong> 19:00 - ???
                </td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- Day #2 -->

        <table>
            <tbody>
            <tr>
                <th class="span12" colspan="5">Day 2 - Saturday Feb. 6th, 2016</th>
            </tr>
            <tr class="bottomline">
                <td>Room</td>
                <td>Grand Ballrooom</td>
                <td>Key Biscayne #1 (front)</td>
                <td>Key Biscayne #2 (rear)</td>
                <td>Key West Ballroom</td>
            </tr>
            <tr class="bottomline">
                <td class="span2">9:00 - 10:00</td>
                <td class="keyrow" colspan="4">Day 2 Opening Keynote - in Grand Ballroom<br />
                    "TBA"<br />
                    <a title="Speaker: Jessica Dunbar" href="/speakers#jessica-dunbar">Jessica Dunbar</a></td>
            </tr>
            <tr class="bottomline">
                <td>10:15 - 11:15</td>
                <td class="span4"><a title="Talk: Asynchronous PHP" href="/talks#talkurl"><strong>Asynchronous PHP</strong></a><br />
                    - <a title="Speaker: Christopher Pitt" href="/speakers#speakerurl">Christopher Pitt</a> -</td>
                <td class="span4"><a title="Talk: Acceptance &amp; Functional Testing with Codeception" href="/talks#talkurl"><strong>Acceptance &amp; Functional Testing with Codeception</strong></a><br />
                    - <a title="Speaker: Joe Ferguson" href="/speakers#speakerurl">Joe Ferguson</a> -</td>
                <td class="span4"><a title="Talk: You Can UX Too: Avoiding the Programmer's User Interface" href="/talks#talkurl"><strong>You Can UX Too: Avoiding the Programmer's User Interface</strong></a><br />
                    - <a title="Speaker: Eryn O'Neil" href="/speakers#speakerurl">Eryn O'Neil</a> -</td>
                <td class="span4"><a title="Talk: 30 Skills to Master to Become a Senior Software Engineer" href="/talks#talkurl"><strong>30 Skills to Master to Become a Senior Software Engineer</strong></a><br />
                    - <a title="Speaker: Sean Coates" href="/speakers#speakerurl">Sean Coates</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>11:30 - 12:30</td>
                <td class="span4"><a title="Talk: Into the ZF2 Service Manager" href="/talks#talkurl"><strong>Into the ZF2 Service Manager</strong></a><br />
                    - <a title="Speaker: Chris Tankersley" href="/speakers#speakerurl">Chris Tankersley</a> -</td>
                <td class="span4"><a title="Talk: Building Real-Time Data Pipelines" href="/talks#talkurl"><strong>Building Real-Time Data Pipelines</strong></a><br />
                    - <a title="Speaker: Samantha Quiñones" href="/speakers#speakerurl">Samantha Quiñones</a> -</td>
                <td class="span4"><a title="Talk: MySQL's JSON Data Type" href="/talks#talkurl"><strong>MySQL's JSON Data Type</strong></a><br />
                    - <a title="Speaker: Dave Stokes" href="/speakers#speakerurl">Dave Stokes</a> -</td>
                <td class="span4"><a title="Talk: Interoperability and PHP in the EdTech Industry" href="/talks#talkurl"><strong>Interoperability and PHP in the EdTech Industry</strong></a><br />
                    - <a title="Speaker: Jeremy Lindblom" href="/speakers#speakerurl">Jeremy Lindblom</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>12:30 - 13:30</td>
                <td class="lunch" colspan="4">Lunch</td>
            </tr>
            <tr class="bottomline">
                <td>13:30 - 14:30</td>
                <td class="keyrow" colspan="4">Day 2 Lunch Keynote - in Grand Ballroom<br />
                    "TBA"<br />
                    <a title="Speaker: Sharon Steed" href="/speakers#sharon-steed">Sharon Steed</a></td>
            </tr>
            <tr class="bottomline">
                <td>14:45 - 15:45</td>
                <td class="span4"><a title="Talk: Performance Testing for Modern Apps" href="/talks#talkurl"><strong>Performance Testing for Modern Apps</strong></a><br />
                    - <a title="Speaker: Dustin Whittle" href="/speakers#speakerurl">Dustin Whittle</a> -</td>
                <td class="span4"><a title="Talk: Growing your filesystem." href="/talks#talkurl"><strong>Growing your filesystem.</strong></a><br />
                    - <a title="Speaker: Frank de Jonge" href="/speakers#speakerurl">Frank de Jonge</a> -</td>
                <td class="span4"><a title="Talk: Taking the Web Offline" href="/talks#talkurl"><strong>Taking the Web Offline</strong></a><br />
                    - <a title="Speaker: Steve Grunwell" href="/speakers#speakerurl">Steve Grunwell</a> -</td>
                <td class="span4"><a title="Talk: Exploiting the Brain for Fun & Profit" href="/talks#talkurl"><strong>Exploiting the Brain for Fun & Profit</strong></a><br />
                    - <a title="Speaker: Alena Holligan" href="/speakers#speakerurl">Alena Holligan</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>16:00 - 17:00</td>
                <td class="span4"><a title="Talk: Microservices: Packs small, plays BIG!" href="/talks#talkurl"><strong>Microservices: Packs small, plays BIG!</strong></a><br />
                    - <a title="Speaker: Stephan Hochdorfer" href="/speakers#speakerurl">Stephan Hochdorfer</a> -</td>
                <td class="span4"><a title="Talk: Adventures in Symfony2 - Building an MMO-RPG" href="/talks#talkurl"><strong>Adventures in Symfony2 - Building an MMO-RPG</strong></a><br />
                    - <a title="Speaker: Margaret Staples" href="/speakers#speakerurl">Margaret Staples</a> -</td>
                <td class="span4"><a title="Talk: /Regex makes me want to (weep|give up|(╯°□°)╯︵ ┻━┻)\.?/i" href="/talks#talkurl"><strong>/Regex makes me want to (weep|give up|(╯°□°)╯︵ ┻━┻)\.?/i</strong></a><br />
                    - <a title="Speaker: Brett Florio" href="/speakers#speakerurl">Brett Florio</a> -</td>
                <td class="span4"><a title="Talk: The WordPress REST API" href="/talks#talkurl"><strong>The WordPress REST API</strong></a><br />
                    - <a title="Speaker: David Bisset" href="/speakers#speakerurl">David Bisset</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>17:15 - 18:15</td>
                <td class="span4"><a title="Talk: From Idea to Prototype in 50 Minutes with Laravel" href="/talks#talkurl"><strong>From Idea to Prototype in 50 Minutes with Laravel</strong></a><br />
                    - <a title="Speaker: Matt Stauffer" href="/speakers#speakerurl">Matt Stauffer</a> -</td>
                <td class="span4"><a title="Talk: The continuous PHP Pipeline" href="/talks#talkurl"><strong>The continuous PHP Pipeline</strong></a><br />
                    - <a title="Speaker: Michelangelo van Dam" href="/speakers#speakerurl">Michelangelo van Dam</a> -</td>
                <td class="span4"><a title="Talk: Functional ES6 JavaScript" href="/talks#talkurl"><strong>Functional ES6 JavaScript</strong></a><br />
                    - <a title="Speaker: Luis Atencio" href="/speakers#speakerurl">Luis Atencio</a> -</td>
                <td class="span4"><a title="Talk: Smiling From the Wrists Down: Customer Service for Developers" href="/talks#talkurl"><strong>Smiling From the Wrists Down: Customer Service for Developers</strong></a><br />
                    - <a title="Speaker: Heather White" href="/speakers#speakerurl">Heather White</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>18:15 - 19:15</td>
                <td class="keyrow" colspan="4"><strong>Closing Keynote - in Grand Ballroom</strong><br />
                    "TBA"<br />
                    <a title="Speaker: Cal Evans" href="/speakers#cal-evans">Cal Evans</a></td>
            </tr>
            <tr>
                <td>19:15 - 19:45</td>
                <td class="keyrow" colspan="4"><strong>Thank you & Prizes</strong><br />
                    Adam Culp</td>
            </tr>
            </tbody>
        </table>
        <hr />
    </div>

</div>