<div class="page-header">
    <h1>Schedule & Layout</h1>
</div>
<div id="block-mine">
    <div id="schedule">

        <!-- Speakers, Talks, and Tutorials links -->
        
        <h3>Related Links:</h3>
        <div style="text-align: center">
            <a class="btn btn-large btn-info" href="/speakers" title="Full Speakers List">Full Speakers List</a>&nbsp;&nbsp;
            <a class="btn btn-large btn-info" href="/talks" title="Full Talks List">Full Talks List</a>&nbsp;&nbsp;
            <a class="btn btn-large btn-info" href="/tutorials" title="Full Tutorials List">Full Tutorials List</a>
            <a class="btn btn-large btn-info" href="/keynotes" title="Full Keynote List">Full Keynote List</a><br /><br />
        </div>
    
        <!-- Overall details of side rooms -->
        
        <table>
            <tbody>
            <tr class="bottomline">
                <th class="span12" colspan="4">Venue room assignments for the conference</th>
            </tr>
            <tr class="bottomline">
                <td class="span3"><strong>Grand Ballroom</strong></td>
                <td>Keynotes and sessions throughout each day</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key Biscayne #1</strong></td>
                <td>Sessions throughout each day</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key Biscayne #2</strong></td>
                <td>Sessions throughout each day</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key West Ballroom</strong></td>
                <td>Tutorial Session and other activities</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key Largo #1</strong></td>
                <td>Registration and Support</td>
            </tr>
            <tr class="bottomline">
                <td ><strong>Key Largo #2 and #3</strong></td>
                <td>Sponsor interaction area and coffee/snacks each day</td>
            </tr>
            <tr>
                <td ><strong>Key Largo #4</strong></td>
                <td>Wifi lounge and Uncon track each day</td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- hotel layout image -->
        
        <img src="/img/hotel_layout.png" alt="Conference Layout Image" />
        <hr />

        <!-- Pre-Conference -->

        <!-- <div class="f_legend"><div class="tag small magento" title="Magento">M</div>= Magento &nbsp; <div class="tag small laravel" title="Laravel">L</div>= Laravel &nbsp; <div class="tag small wordpress" title="WordPress">W</div>= WordPress &nbsp; <div class="tag small drupal" title="Drupal">D</div>= Drupal &nbsp; <div class="tag small joomla" title="Joomla!">J</div>= Joomla! &nbsp; <div class="tag small zendframework" title="Zend Framework">Z</div>= Zend Framework &nbsp; <div class="tag small symfony" title="Symfony">S</div>= Symfony &nbsp; <div class="tag small cakephp" title="CakePHP">C</div>= CakePHP &nbsp; </div> -->

        <table>
            <tbody>
            <tr>
                <th class="span12" colspan="5">Wednesday Feb. 7th, 2018</th>
            </tr>
            <tr>
                <td class="span2">17:30 - 19:30</td>
                <td class="keyrow" colspan="4"><strong>Happy Hour</strong> Atrium bar</td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- Tutorial Day -->
        
        <table>
            <tbody>
            <tr>
                <th class="span12"  colspan="5">Tutorial Day - Thursday Feb. 8th, 2018</th>
            </tr>
            <tr class="bottomline">
                <td>Room</td>
                <td>Grand Ballrooom</td>
                <td>Key Biscayne #1 (front)</td>
                <td>Key Biscayne #2 (rear)</td>
                <td>Key West Ballroom</td>
            </tr>
            <tr class="bottomline">
                <td class="span2">8:00 - 9:00</td>
                <td class="keyrow" colspan="4"><strong>Tutorial Registration Opens</strong> in Key Largo #1</td>
            </tr>
            <tr class="bottomline">
                <td>9:00 - 12:00</td>
                <td class="span3"><a title="Tutorial: Start testing your PHP code" href="/tutorials#start-testing-your-php-code"><strong>Start testing your PHP code</strong></a><br />
                    - <a title="Speaker: Jason McCreary" href="/speakers#jason-mccreary">Jason McCreary</a> -</td>
                <td class="span3"><a title="Tutorial: Building Modern APIs in Expressive" href="/tutorials#building-modern-apis-in-expressive"><strong>Building Modern APIs in Expressive</strong></a><br />
                    - <a title="Speaker: Rob Allen" href="/speakers#rob-allen">Rob Allen</a> -</td>
                <td class="span3"><a title="Tutorial: Dive into Symfony 4 &amp; Flex!" href="/tutorials#dive-into-symfony-4-and-flex"><strong>Dive into Symfony 4 &amp; Flex!</strong></a><br />
                    - <a title="Speaker: Ryan Weaver" href="/speakers#ryan-weaver">Ryan Weaver</a> -</td>
                <td class="span3"><a title="Tutorial: Guide to UX Testing with Assistive Technology" href="/tutorials#guide-to-ux-testing-with-assistive-technology"><strong>Guide to UX Testing with Assistive Technology</strong></a><br />
                    - <a title="Speaker: Andrea Skeries" href="/speakers#andrea-skeries">Andrea Skeries</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>12:00 - 13:00</td>
                <td class="lunch" colspan="4">Lunch</td>
            </tr>
            <tr class="bottomline">
                <td>13:00 - 16:00</td>
                <td class="span3"><a title="Tutorial: Defensive Coding Crash Course" href="/tutorials#defensive-coding-crash-course"><strong>Defensive Coding Crash Course</strong></a><br />
                    - <a title="Speaker: Mark Niebergall" href="/speakers#mark-niebergall">Mark Niebergall</a> -</td>
                <td class="span3"><a title="Tutorial: Create an API-centric System for Web and Mobile" href="/tutorials#create-an-api-centric-system-for-web-and-mobile"><strong>Create an API-centric System for Web and Mobile</strong></a><br />
                    - <a title="Speaker: Christian Varela" href="/speakers#christian-varela">Christian Varela</a> -</td>
                <td class="span3"><a title="Tutorial: PHP Extension Writing" href="/tutorials#php-extension-writing"><strong>PHP Extension Writing</strong></a><br />
                    - <a title="Speaker: Sara Golemon" href="/speakers#sara-golemon">Sara Golemon</a> -</td>
                <td class="span3"><a title="Tutorial: TBA" href="/tutorials#tba"><strong>None</strong></a><br />
                    - <a title="Speaker: TBA" href="/speakers#tba">None</a> -</td>
            </tr>
            <tr>
                <td>17:30 - 19:30</td>
                <td class="keyrow" colspan="4"><strong>Happy Hour</strong> Atrium bar</td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- Day #1 -->
        
        <table>
            <tbody>
            <tr>
                <th class="span12" colspan="4">Day 1 - Friday Feb. 9th, 2018</th>
            </tr>
            <tr class="bottomline">
                <td>Room</td>
                <td>Grand Ballrooom</td>
                <td>Key Biscayne #1 (front)</td>
                <td>Key Biscayne #2 (rear)</td>
            </tr>
            <tr class="bottomline">
                <td class="span2">8:00 - 9:00</td>
                <td colspan="3"><strong>Conference Registration Opens</strong> in Key Largo #1</td>
            </tr>
            <tr class="bottomline">
                <td>9:00 - 10:00</td>
                <td class="keyrow" colspan="3">Opening Keynote - in Grand Ballroom<br />
                    <a title="Keynote: Communicate!" href="/keynotes#communicate">Communicate!</a><br />
                    - <a title="Speaker: Cal Evans" href="/speakers#cal-evans">Cal Evans</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>10:15 - 11:15</td>
                <td class="span4"><a title="Talk: Protect your API with OAuth2" href="/talks#protect-your-api-with-oauth2"><strong>Protect your API with OAuth2</strong></a><br />
                    - <a title="Speaker: Rob Allen" href="/speakers#rob-allen">Rob Allen</a> -</td>
                <td class="span4"><a title="Talk: MySQL 8" href="/talks#mysql-8"><strong>MySQL 8</strong></a><br />
                    - <a title="Speaker: Dave Stokes" href="/speakers#dave-stokes">Dave Stokes</a> -</td>
                <td class="span4"><a title="Talk: Securing Web Services: Fundamentals, Lessons Learnt, Common Vulnerabilities and Security Strategies" href="/talks#securing-web-services-fundamentals-lessons-learnt-common-vulnerabilities-and-security-strategies"><strong>Securing Web Services: Fundamentals, <br />Lessons Learnt, Common Vulnerabilities <br />and Security Strategies</strong></a><br />
                    - <a title="Speaker: Amrita Jain" href="/speakers#amrita-jain">Amrita Jain</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>11:30 - 12:30</td>
                <td class="span4"><a title="Talk: Advanced PHP Simplified" href="/talks#advanced-php-simplified"><strong>Advanced PHP Simplified</strong></a><br />
                    - <a title="Speaker: Mark Niebergall" href="/speakers#mark-niebergall">Mark Niebergall</a> -</td>
                <td class="span4"><a title="Talk: Philosophy in Code: I Kant Even" href="/talks#philosophy-in-code-i-kant-even"><strong>Philosophy in Code: I Kant Even</strong></a><br />
                    - <a title="Speaker: Margaret Staples" href="/speakers#margaret-staples">Margaret Staples</a> -</td>
                <td class="span4"><a title="Talk: Domain-Driven Data" href="/talks#domain-driven-data"><strong>Domain-Driven Data</strong></a><br />
                    - <a title="Speaker: Bradley Holt" href="/speakers#bradley-holt">Bradley Holt</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>12:30 - 13:30</td>
                <td class="lunch" colspan="3">Lunch</td>
            </tr>
            <tr class="bottomline">
                <td>13:30 - 14:30</td>
                <td class="keyrow" colspan="3">Lunch Keynote - in Grand Ballroom<br />
                    <a title="Keynote: How to Go from Developer to Stakeholder" href="/keynotes#how-to-go-from-developer-to-stakeholder">How to Go from Developer to Stakeholder</a><br />
                    - <a title="Speaker: Ann Gaffigan" href="/speakers#ann-gaffigan">Ann Gaffigan</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>14:45 - 15:45</td>
                <td class="span4"><a title="Talk: Xdebug" href="/talks#xdebug"><strong>Xdebug</strong></a><br />
                    - <a title="Speaker: Derick Rethans" href="/speakers#derick-rethans">Derick Rethans</a> -</td>
                <td class="span4"><a title="Talk: Make your application Expressive" href="/talks#make-your-application-expressive"><strong>Make your application Expressive</strong></a><br />
                    - <a title="Speaker: Christian Varela" href="/speakers#christian-varela">Christian Varela</a> -</td>
                <td class="span4"><a title="Talk: Converting Your DEV Environment to a Docker Stack" href="/talks#converting-your-dev-environment-to-a-docker-stack"><strong>Converting Your DEV Environment <br />to a Docker Stack</strong></a><br />
                    - <a title="Speaker: Dana Luther" href="/speakers#dana-luther">Dana Luther</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>16:00 - 17:00</td>
                <td class="span4"><a title="Talk: Containers are a pile of lies!" href="/talks#containers-are-a-pile-of-lies"><strong>Containers are a pile of lies!</strong></a><br />
                    - <a title="Speaker: Larry Garfield" href="/speakers#larry-garfield">Larry Garfield</a> -</td>
                <td class="span4"><a title="Talk: Is the future of computing deviceless?" href="/talks#is-the-future-of-computing-deviceless"><strong>Is the future of computing deviceless?</strong></a><br />
                    - <a title="Speaker: Ibis Fonte" href="/speakers#ibis-fonte">Ibis Fonte</a> -</td>
                <td class="span4"><a title="Talk: Practicing YAGNI (You Aren't Gonna Need It)" href="/talks#practicing-yagni"><strong>Practicing YAGNI (You Aren't Gonna Need It)</strong></a><br />
                    - <a title="Speaker: Jason McCreary" href="/speakers#jason-mccreary">Jason McCreary</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>17:15 - 18:15</td>
                <td class="span4"><a title="Talk: How PHP Ticks" href="/talks#how-php-ticks"><strong>How PHP Ticks</strong></a><br />
                    - <a title="Speaker: Sara Golemon" href="/speakers#sara-golemon">Sara Golemon</a> -</td>
                <td class="span4"><a title="Talk: How to beat memory bloat with generators" href="/talks#how-to-beat-memory-bloat-with-generators"><strong>How to beat memory bloat with generators</strong></a><br />
                    - <a title="Speaker: Korvin Szanto" href="/speakers#korvin-szanto">Korvin Szanto</a> -</td>
                <td class="span4"><a title="Talk: Squash Accessibility Bugs" href="/talks#squash-accessibility-bugs"><strong>Squash Accessibility Bugs</strong></a><br />
                    - <a title="Speaker: Andrea Skeries" href="/speakers#andrea-skeries">Andrea Skeries</a> -</td>
            </tr>
            <tr>
                <td>Evening</td>
                <td class="keyrow" colspan="3">
                    <strong>Panel Discussion: "TBA"</strong><br />
                    <a title="Speaker: Adam Culp" href="/speakers#adam-culp">Moderator: Adam Culp</a><br /><br />
                    Hack Event in Key West Ballroom - Hosted by: TBA<br /><br />
                    <strong>Happy Hour</strong> from 18:30 - 19:30 featuring <strong>"What's It?" Game hosted by Adam Culp</strong> in Grand Ballroom<br />
                </td>
            </tr>
            </tbody>
        </table>
        <hr />
        
        <!-- Day #2 -->

        <table>
            <tbody>
            <tr>
                <th class="span12" colspan="4">Day 2 - Saturday Feb. 10th, 2018</th>
            </tr>
            <tr class="bottomline">
                <td>Room</td>
                <td>Grand Ballrooom</td>
                <td>Key Biscayne #1 (front)</td>
                <td>Key Biscayne #2 (rear)</td>
            </tr>
            <tr class="bottomline">
                <td class="span2">9:00 - 10:00</td>
                <td class="keyrow" colspan="3">Day 2 Opening Keynote - in Grand Ballroom<br />
                    <a title="Keynote: How to Communicate When You are from Mars and the Business is from Venus" href="/keynotes#how-to-communicate-when-you-are-from-mars-and-the-business-is-from-venus">How to Communicate When You are from Mars and the Business is from Venus</a><br />
                    - <a title="Speaker: Nancy Gaines" href="/speakers#nancy-gaines">Nancy Gaines</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>10:15 - 11:15</td>
                <td class="span4"><a title="Talk: Let's Talk Scope" href="/talks#lets-talk-scope"><strong>Let's Talk Scope</strong></a><br />
                    - <a title="Speaker: Alena Holligan" href="/speakers#alena-holligan">Alena Holligan</a> -</td>
                <td class="span4"><a title="Talk: SlimPHP - When you don't need the kitchen sink" href="/talks#slimphp-when-you-dont-need-the-kitchen-sink"><strong>SlimPHP - When you don't need the kitchen sink</strong></a><br />
                    - <a title="Speaker: Joe Ferguson" href="/speakers#joe-ferguson">Joe Ferguson</a> -</td>
                <td class="span4"><a title="Talk: Win Big, Cache Out" href="/talks#win-big-cache-out"><strong>Win Big, Cache Out</strong></a><br />
                    - <a title="Speaker: Ashley Hutson" href="/speakers#ashley-hutson">Ashley Hutson</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>11:30 - 12:30</td>
                <td class="span4"><a title="Talk: 10 Things I Hate About Your API" href="/talks#10-things-i-hate-about-your-api"><strong>10 Things I Hate About Your API</strong></a><br />
                    - <a title="Speaker: Amanda Folson" href="/speakers#amanda-folson">Amanda Folson</a> -</td>
                <td class="span4"><a title="Talk: A Review of Code Reviews" href="/talks#a-review-of-code-reviews"><strong>A Review of Code Reviews</strong></a><br />
                    - <a title="Speaker: Chris Russell" href="/speakers#chris-russell">Chris Russell</a> -</td>
                <td class="span4"><a title="Talk: Deploy Scalable and Secure PHP Applications with Kubernetes" href="/talks#deploy-scalable-and-secure-php-applications-with-kubernetes"><strong>Deploy Scalable and Secure PHP <br />Applications with Kubernetes</strong></a><br />
                    - <a title="Speaker: Brent Shaffer" href="/speakers#brent-shaffer">Brent Shaffer</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>12:30 - 13:30</td>
                <td class="lunch" colspan="3">Lunch</td>
            </tr>
            <tr class="bottomline">
                <td>13:30 - 14:30</td>
                <td class="keyrow" colspan="3">Day 2 Lunch Keynote - in Grand Ballroom<br />
                    <a title="Keynote: Forget accessibility - Think inclusive design" href="/keynotes#forget-accessibility-think-inclusive-design">Forget accessibility - Think inclusive design</a><br />
                    - <a title="Speaker: Nicolas Steenhout" href="/speakers#nicolas-steenhout">Nicolas Steenhout</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>14:45 - 15:45</td>
                <td class="span4"><a title="Talk: Cryptography For Beginners" href="/talks#cryptography-for-beginners"><strong>Cryptography For Beginners</strong></a><br />
                    - <a title="Speaker: Adam Englander" href="/speakers#adam-englander">Adam Englander</a> -</td>
                <td class="span4"><a title="Talk: The Voice-First Revolution: Building Google Assistant Apps Using JavaScript" href="/talks#the-voice-first-revolution-building-google-assistant-apps-using-javascript"><strong>The Voice-First Revolution: Building Google Assistant Apps Using JavaScript</strong></a><br />
                    - <a title="Speaker: Kesha Williams" href="/speakers#kesha-williams">Kesha Williams</a> -</td>
                <td class="span4"><a title="Talk: Functional programming for the Advanced Beginner" href="/talks#functional-programming-for-the-advanced-beginner"><strong>Functional programming for <br />the Advanced Beginner</strong></a><br />
                    - <a title="Speaker: Luis Atencio" href="/speakers#luis-atencio">Luis Atencio</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>16:00 - 17:00</td>
                <td class="span4"><a title="Talk: Essential AWS for PHP Applications" href="/talks#essential-aws-for-php-applications"><strong>Essential AWS for PHP Applications</strong></a><br />
                    - <a title="Speaker: Michael Moussa" href="/speakers#michael-moussa">Michael Moussa</a> -</td>
                <td class="span4"><a title="Talk: Crescent Wrenches and Debuggers: Building Your Own Toolkit For Rational Inquiry" href="/talks#crescent-wrenches-and-debuggers-building-your-own-toolkit-for-rational-inquiry"><strong>Crescent Wrenches and Debuggers: Building Your Own Toolkit For Rational Inquiry</strong></a><br />
                    - <a title="Speaker: Kerri Miller" href="/speakers#kerri-miller">Kerri Miller</a> -</td>
                <td class="span4"><a title="Talk: Virtual Machine, Container, or Serverless" href="/talks#virtual-machine-container-or-serverless"><strong>Virtual Machine, Container, or Serverless</strong></a><br />
                    - <a title="Speaker: Terrence Ryan" href="/speakers#terrence-ryan">Terrence Ryan</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>17:15 - 18:15</td>
                <td class="span4"><a title="Talk: OSS Commerce Melee" href="/talks#oss-commerce-melee"><strong>OSS Commerce Melee</strong></a><br />
                    - <a title="Speaker: Ben Marks" href="/speakers#ben-marks">Ben Marks</a> -</td>
                <td class="span4"><a title="Talk: Vulnerability Scanning for your Website" href="/talks#vulnerability-scanning-for-your-website"><strong>Vulnerability Scanning for your Website</strong></a><br />
                    - <a title="Speaker: Lisa Bock" href="/speakers#lisa-bock">Lisa Bock</a> -</td>
                <td class="span4"><a title="Talk: You Were Lied To About Optimization" href="/talks#you-were-lied-to-about-optimization"><strong>You Were Lied To About Optimization</strong></a><br />
                    - <a title="Speaker: Chris Tankersley" href="/speakers#chris-tankersley">Chris Tankersley</a> -</td>
            </tr>
            <tr class="bottomline">
                <td>18:30 - 19:30</td>
                <td class="keyrow" colspan="3"><strong>Closing Keynote - in Grand Ballroom</strong><br />
                    <a title="Keynote: TBA" href="/keynotes#tba">TBA</a><br />
                    - <a title="Speaker: Federico Lara" href="/speakers#federico-lara">Federico Lara</a> -</td>
            </tr>
            <tr>
                <td>19:30 - 19:45</td>
                <td class="keyrow" colspan="3"><strong>Thank you & Prizes</strong><br />
                    - <a title="Speaker: Adam Culp" href="/speakers#adam-culp">Adam Culp</a> -</td>
            </tr>
            </tbody>
        </table>
        <hr />
    </div>

</div>