<div class="page-header">
    <h1>Speakers</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        Below is the full list of speakers who will be presenting the talks, tutorials and keynotes of the SunshinePHP Developer Conference.<br /><br />
    
        NOTE: In order to hear these wonderful speakers a registration is required using the <a href="http://sunshinephp.com/register" title="SunshinePHP Registration">Registration page</a>. Also please note that the tutorials require an additional ticket also available using the <a href="http://sunshinephp.com/register" title="SunshinePHP Registration">registration page</a>.
    </p>
    
    <div style="padding-left: 30px;">
        
        <!-- <div id="speakertag" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#speakertag" title="SpeakerName"><img src="/img/speakers/speaker_name.png" alt="SpeakerName" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>SpeakerName</h2>

                <strong>Bio:</strong> speaker_bio<br /><br />

                <a href="/talks#talk_tag" title="Talk: talk_title">Talk: talk_title</a><br /><br />

                <a href="/tutorials#tutorial_tag" title="Tutorial: tutorial_title">Tutorial: tutorial_title</a><br /><br />
            </div>
        </div> -->
        
        <div id="adam-culp" class=talk_tag"clearfix">
            <hr />
        
            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#adam-culp" title="Adam Culp"><img src="/img/speakers/adam_culp.jpg" alt="Adam Culp" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Adam Culp (MC)</h2>
            
                <strong>Bio:</strong> Adam Culp (@AdamCulp) author of "Refactoring 101" and consultant at Zend Technologies is passionate about developing with PHP and contributes to many open source projects. He organizes the SunshinePHP Developer Conference and the South Florida PHP Users Group (SoFloPHP) where he enjoys helping others write good code, implement standards, refactor efficiently, and incorporate unit and functional testing into their projects. He is a Zend Certified PHP 5.3 Engineer, is a voting member of the PHP-Fig, and holds a seat on the Zend Framework Certification Advisory Board. You can also find him on his Run Geek Radio podcast and GeekyBoy technical blog. When he is not coding or contributing to various developer communities, he can be found hiking around the United States National Parks, teaching judo, or long(ultra) distance running.<br /><br />

            </div>
        </div>

        <?php
        $badArray = ["'", ":", "(", ")", ",", "!", "?", "."];
        $user_id = 0;
        if ($sessions):
            foreach ($sessions as $session):

                $addAnotherTalk = false;

                if ($user_id == $session['user_id']) {

                    $addAnotherTalk = true;
                }

                // this is a new speaker, end the previous one
                if (!$addAnotherTalk) {
                ?>
    </div>
</div>

                <div id="<?=strtolower($session['first_name'])?>-<?=strtolower($session['last_name'])?>" class="clearfix">
                    <hr />

                    <div class="span3" style="height:225px; width:225px;">
                        <a href="/speakers#<?=strtolower($session['first_name'])?>-<?=strtolower($session['last_name'])?>" title="<?=$session['first_name']?> <?=$session['last_name']?>"><img src="/img/speakers/<?=$session['photo_name']?>" alt="<?=$session['first_name']?> <?=$session['last_name']?>" /></a>
                    </div>
                    <div class="span5" style="text-align: justify;">
                        <h2><?=$session['first_name']?> <?=$session['last_name']?></h2>

                        <strong>Bio:</strong> <?=nl2br($session['bio'])?><br /><br />

                        <a href="/talks#<?=preg_replace("/[\s_]/", "-", strtolower(str_replace($badArray, "", $session['title'])))?>" title="Talk: <?=$session['title']?>">Talk: <?=$session['title']?></a><br /><br />

                        <?php
                        } // end !addAnotherTalk

                        if ($addAnotherTalk) {

                            // #1 add a tutorial block if this is a tutorial
                            if ($session['type'] == 'tutorial') {
                                ?>

                                <a href="/tutorials#<?= preg_replace("/[\s_]/", "-", strtolower(str_replace($badArray, "", $session['title']))) ?>"
                                   title="Tutorial: <?= $session['title'] ?>">Tutorial: <?= $session['title'] ?></a>
                                <br/><br/>

                                <?php
                            } // end tutorial add

                            // #2 add a regular block if this is a regular
                            if ($session['type'] == 'regular') {

                                ?>

                                <a href="/talks#<?= preg_replace("/[\s_]/", "-", strtolower(str_replace($badArray, "", $session['title']))) ?>"
                                   title="Talk: <?= $session['title'] ?>">Talk: <?= $session['title'] ?></a><br/><br/>

                                <?php
                            } // end regular add

                            // #3 add a keynote block if this is a keynote
                            if ($session['type'] == 'keynote') {

                                ?>

                                <a href="/keynotes#<?= preg_replace("/[\s_]/", "-", strtolower(str_replace($badArray, "", $session['title']))) ?>"
                                   title="Talk: <?= $session['title'] ?>">Keynote: <?= $session['title'] ?></a><br/>
                                <br/>

                                <?php
                            } // end keynote add

                        } // end addAnotherTalk


            $user_id = $session['user_id'];

            endforeach; // end foreach(sessions)
        endif; // end if(sessions)
        ?>

    </div>
    <hr />
</div>