<div class="page-header">
    <h1>Speakers</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        Below is the full list of speakers who will be presenting the talks, tutorials and keynotes of the SunshinePHP Developer Conference.<br /><br />
    
        NOTE: In order to hear these wonderful speakers a registration is required using the <a href="http://sunshinephp.com/register" title="SunshinePHP Registration">Registration page</a>. Also please note that the tutorials require an additional ticket also available using the <a href="http://sunshinephp.com/register" title="SunshinePHP Registration">registration page</a>.
    </p>
    
    <div style="padding-left: 30px;">
        
        <!-- <div id="speakertag" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#speakertag" title="SpeakerName"><img src="/img/speakers/speaker_name.png" alt="SpeakerName" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>SpeakerName</h2>

                <strong>Bio:</strong> speaker_bio<br /><br />

                <a href="/talks#talk_tag" title="Talk: talk_title">Talk: talk_title</a><br /><br />

                <a href="/tutorials#tutorial_tag" title="Tutorial: tutorial_title">Tutorial: tutorial_title</a><br /><br />
            </div>
        </div> -->
        
        <div id="adam-culp" class=talk_tag"clearfix">
            <hr />
        
            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#adam-culp" title="Adam Culp"><img src="/img/speakers/adam_culp.jpg" alt="Adam Culp" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Adam Culp (MC)</h2>
            
                <strong>Bio:</strong> Adam Culp (@AdamCulp) author of "Refactoring 101" and consultant at Zend Technologies is passionate about developing with PHP and contributes to many open source projects. He organizes the SunshinePHP Developer Conference and the South Florida PHP Users Group (SoFloPHP) where he enjoys helping others write good code, implement standards, refactor efficiently, and incorporate unit and functional testing into their projects. He is a Zend Certified PHP 5.3 Engineer, is a voting member of the PHP-Fig, and holds a seat on the Zend Framework Certification Advisory Board. You can also find him on his Run Geek Radio podcast and GeekyBoy technical blog. When he is not coding or contributing to various developer communities, he can be found hiking around the United States National Parks, teaching judo, or long(ultra) distance running.<br /><br />

            </div>
        </div>

        <div id="amrita-jain" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#amrita-jain" title="Amrita Jain"><img src="/img/speakers/amrita_jain.png" alt="Amrita Jain" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Amrita Jain</h2>

                <strong>Bio:</strong> Amrita Jain has a strong background in architecting scalable web services and cloud infrastructures. She earned her Masters in CS from Cornell and has held key positions in several companies of varying sizes, thus building a well-rounded technology perspective. Currently, she is senior manager of engineering at Glassdoor. Previously she worked as the Director of WebServices at Beachbody LLC. where the tech backbone designed by her team serves millions of customers across America and Europe. She is an active member of several southern California tech meetups and regularly presents her experiences and innovations in developing scalable and secure Microservice architectures.<br /><br />

                <a href="/talks#device-independent-api-design" title="Talk: Device Independent API design">Talk: Device Independent API design</a><br /><br />
            </div>
        </div>

        <div id="andrew-cassell" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#andrew-cassell" title="Andrew Cassell"><img src="/img/speakers/andrew_cassell.png" alt="Andrew Cassell" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Andrew Cassell</h2>

                <strong>Bio:</strong> Andrew Cassell is a Senior Backend Developer for CuriosityStream, the award-winning documentary streaming service launched by Discovery founder John Hendricks.<br /><br />

                <a href="/talks#immutability-to-save-an-ever-changing-world" title="Talk: Immutability to Save an Ever-Changing World">Talk: Immutability to Save an Ever-Changing World</a><br /><br />
            </div>
        </div>

        <div id="ben-marks" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#ben-marks" title="Ben Marks"><img src="/img/speakers/ben_marks.png" alt="Ben Marks" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Ben Marks</h2>

                <strong>Bio:</strong> Ben began his career in PHP building commercial sites in 2003, focusing on Magento since 2008 and joining the ranks of Magento as their sole evangelist in 2014. He believes that the boundless requirements of commerce provide some of the best fodder for development (and for conference discussions). Always a learner, frequently a teacher, his approach to speaking and attending conferences is to find the story, enjoyment, and (often) humor in every situation.<br /><br />

                <a href="/talks#pwa-for-php-developers" title="Talk: PWA for PHP Developers">Talk: PWA for PHP Developers</a><br /><br />
            </div>
        </div>

        <div id="beth-tucker-long" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#beth-tucker-long" title="Beth Tucker Long"><img src="/img/speakers/beth_tucker_long.png" alt="Beth Tucker Long" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Beth Tucker Long</h2>

                <strong>Bio:</strong> Beth Tucker Long is a PHP developer and co-organizer of Madison PHP. You can find her on Twitter (@e3betht) or on her blog (http://www.alittleofboth.com). Beth is a firm believer in promoting community and mentoring. She runs Treeline Design, a web development company, and Playlist Event Music, a DJ company, along with her husband, Chris.<br /><br />

                <a href="/talks#accessibility-for-everyone" title="Talk: Accessibility for Everyone">Talk: Accessibility for Everyone</a><br /><br />
            </div>
        </div>

        <div id="brandon-savage" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#brandon-savage" title="Brandon Savage"><img src="/img/speakers/brandon_savage.jpg" alt="Brandon Savage" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Brandon Savage</h2>

                <strong>Bio:</strong> In 2003 Brandon discovered that PHP could automate things that would take a long time to do by hand. Brandon was hooked, and spent every waking hour learning PHP and how to use it for his projects. Brandon began his career working for small shops doing WordPress and Drupal with some custom applications, and then moved on to Mozilla, where he worked on a highly-available big-data project called Socorro.<br /><br />

                Brandon's passions are object-oriented design and well-written code, along with a healthy dose of a "just ship" mentality for solving business problems. Brandon speaks at PHP conferences around the world on a variety of subjects focused on good code, object-oriented design, and getting things done.<br /><br />

                <a href="/talks#the-ten-commandments-of-object-oriented-code" title="Talk: The Ten Commandments of Object-Oriented Code">Talk: The Ten Commandments of Object-Oriented Code</a><br /><br />

                <a href="/tutorials#practical-object-oriented-design-principles" title="Tutorial: Practical Object-Oriented Design Principles">Tutorial: Practical Object-Oriented Design Principles</a><br /><br />
            </div>
        </div>

        <div id="brian-johnson" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#brian-johnson" title="Brian Johnson"><img src="/img/speakers/brian_johnson.jpg" alt="Brian Johnson" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Brian Johnson</h2>

                <strong>Bio:</strong> Brian is principal engineer at PayLease, a leader in payments processing and other property management services. He has been working with PHP for over 5 years, following a decade-long stint as a Java developer. He is enthusiastic about object oriented design, dependency management and unit testing. He makes his home in Colorado Springs, CO where he organizes the Peak PHP user group.<br /><br />

                <a href="/talks#unlock-the-mystery-of-phpunit" title="Talk: Unlock The Mystery of PHPUnit">Talk: Unlock The Mystery of PHPUnit</a><br /><br />
            </div>
        </div>

        <div id="chris-cornutt" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#chris-cornutt" title="Chris Cornutt"><img src="/img/speakers/chris_cornutt.jpg" alt="Chris Cornutt" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Chris Cornutt</h2>

                <strong>Bio:</strong> For the last 12+ years, Chris has been involved in the PHP community in one way or another. These days he's the Senior Editor of PHPDeveloper.org, lead author for Websec.io, a site dedicated to teaching developers about security, and the Securing PHP project. He's also written for several PHP publications and has spoken at conferences in both the U.S. and Europe on security-related topics. He's also an organizer of the Dallas PHP User Group and the Lone Star PHP Conference and works as an Application Security Engineer for Duo Security.<br /><br />

                <a href="/talks#securing-legacy-applications" title="Talk: Securing Legacy Applications">Talk: Securing Legacy Applications</a><br /><br />

                <a href="/tutorials#pentesting-for-developers" title="Tutorial: Pentesting for Developers">Tutorial: Pentesting for Developers</a><br /><br />
            </div>
        </div>

        <div id="chris-hartjes" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#chris-hartjes" title="Chris Hartjes"><img src="/img/speakers/chris_hartjes.jpg" alt="Chris Hartjes" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Chris Hartjes</h2>

                <strong>Bio:</strong> Chris Hartjes has been building web applications of all shapes and sizes since 1998 mostly with PHP and yelling at anyone who will listen about writing tests and using automation to make your life easier since 2005. Monday to Thursday he currently works for Mozilla as part of the Firefox Test Engineering team doing testing of the growing number of services Firefox relies on. On Fridays he tries to work on his ever-growing collection of books, videos, and training sessions that he offers through http://grumpy-learning.com. He works from his home office located in the snowy wilds of Southwestern Ontario, Canada.<br /><br />

                <a href="/keynotes#confessions-of-a-not-so-accidental-leader" title="Keynote: Confessions Of a Not-So-Accidental Leader">Keynote: Confessions Of a Not-So-Accidental Leader</a><br /><br />
            </div>
        </div>

        <div id="damien-seguy" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#damien-seguy" title="Damien Seguy"><img src="/img/speakers/damien_seguy.jpg" alt="Damien Seguy" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Damien Seguy</h2>

                <strong>Bio:</strong> Damien Seguy is CTO at Exakat Ltd., a company specialized in PHP code quality solutions for the industry. He leads the development of the exakat static analysis engine, that automatically review code for version compatibility, security and clear code. Over the last 17 years Damien has contributed to PHP, as documentation author, elephpant breeder, conference UFO on all continents. He also enjoys machine learning, gremlin, 狮子头 and camembert.<br /><br />

                <a href="/talks#how-does-php-static-analysis-work" title="Talk: How does PHP static analysis work">Talk: How does PHP static analysis work</a><br /><br />

                <a href="/tutorials#php-code-review" title="Tutorial: PHP Code review">Tutorial: PHP Code review</a><br /><br />
            </div>
        </div>

        <div id="dana-luther" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#dana-luther" title="Dana Luther"><img src="/img/speakers/dana_luther.jpg" alt="Dana Luther" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Dana Luther</h2>

                <strong>Bio:</strong> Dana is a Senior Web Application Architect at Envisage International. She has been developing in PHP for over 15 years, and building almost exclusively in the Yii Framework for the last 7 years. She is a graduate of the University of Florida, and works with a small agile group of Yii developers to meet the demands of a diverse international company that serves the needs of international students around the world with over 650,000 monthly visitors and generating over 1,200,000 page views. Dana is one of the co-organizers of the Yii-Jax Meetup group, a regular contributor to the Envisage International Blog and maintains her own blog on the Yii Framework.<br /><br />

                <a href="/talks#docker-alphabet-soup" title="Talk: Docker Alphabet Soup">Talk: Docker Alphabet Soup</a><br /><br />
            </div>
        </div>

        <div id="dave-stokes" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#dave-stokes" title="Dave Stokes"><img src="/img/speakers/dave_stokes.jpg" alt="Dave Stokes" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Dave Stokes</h2>

                <strong>Bio:</strong> Dave Stokes is a MySQL Community Manager for Oracle Corporation.<br /><br />

                <a href="/talks#the-mysql-document-store" title="Talk: The MySQL Document Store">Talk: The MySQL Document Store</a><br /><br />

                <a href="/tutorials#the-mysql-document-store" title="Tutorial: The MySQL Document Store">Tutorial: The MySQL Document Store</a><br /><br />
            </div>
        </div>

        <div id="david-bisset" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#david-bisset" title="David Bisset"><img src="/img/speakers/david_bisset.jpg" alt="David Bisset" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>David Bisset</h2>

                <strong>Bio:</strong> A full-time PHP and WordPress freelancer for 10+ years, David is now a senior PHP developer at EnviraGalleryLLC working on two popular WordPress plugins (Envira Gallery and Soliloquy) used by hundred of thousands of websites. In addition, he also works on the popular WordPress Post Status newsletter, works as a consultant and developer for various PHP and JavaScript side projects, speaker, coding mentor, contributor to various open source projects, and helps run several meetups in South Florida. For the past decade, he has been an organizer of one of the largest and longest running WordPress conferences - WordCamp Miami. Also known for his live tweeting of conferences and a sense of humor he uses to keep him sane.<br /><br />

                When he’s not working you’ll find David enjoying time with his family, debating which Star Trek series is the best, talking to people about tech communities and how they can shape our society for the better, and trying to find new creative ways to use or donate all the tech conference shirts he's collected over the years.<br /><br />

                <a href="/keynotes#dealing-with-development-overload" title="General Session: Dealing With Development Overload">General Session: Dealing With Development Overload</a><br /><br />
            </div>
        </div>

        <div id="demin-yin" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#demin-yin" title="Demin Yin"><img src="/img/speakers/demin_yin.jpg" alt="Demin Yin" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Demin Yin</h2>

                <strong>Bio:</strong> Demin is a staff engineer and technical lead on Glu Mobile’s Design Home team. He has been using PHP primarily since 2000, and has worked for a diverse group of companies throughout his career, from start-ups to some of the Bay Area’s largest international corporations, including eBay, Visa and Glu. For years, Demin has been focused on building high-performance, secure web applications and is always exploring ways to push the limit of PHP. Besides architecting and building backend services with PHP, he works with his teammates on open source projects at Glu to give back to the community.<br /><br />

                <a href="/talks#swoole-4-introducing-the-new-coroutine-design-pattern-in-php" title="Talk: Swoole 4: Introducing the New Coroutine Design Pattern in PHP">Talk: Swoole 4: Introducing the New Coroutine Design Pattern in PHP</a><br /><br />
            </div>
        </div>

        <div id="enrico-zimuel" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#enrico-zimuel" title="Enrico Zimuel"><img src="/img/speakers/enrico_zimuel.png" alt="Enrico Zimuel" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Enrico Zimuel</h2>

                <strong>Bio:</strong> Enrico Zimuel is a developer since 1996. He works as Senior Software Engineer at Rogue Wave Software in the R&D department of Zend open source products. He is a core developer of Apigility, Expressive, and Zend Framework. He has been a Researcher Programmer at the Informatics Institute of the University of Amsterdam. He is a TEDx speaker and regular speaker of international PHP conferences. He is the co-founder of the PHP User Group of Turin (Italy).<br /><br />

                <a href="/talks#the-sodium-crypto-library-of-php-7-2" title="Talk: The Sodium crypto library of PHP 7.2">Talk: The Sodium crypto library of PHP 7.2</a><br /><br />
            </div>
        </div>

        <div id="ian-littman" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#ian-littman" title="Ian Littman"><img src="/img/speakers/ian_littman.jpg" alt="Ian Littman" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Ian Littman</h2>

                <strong>Bio:</strong> When he isn't building or maintaining web applications, primarily of the API variety, for a handful of clients, Ian's probably biking between coffee shops in Austin, Texas or bemoaning the fact that "artificial intelligence" is now merely a marketing term. He also helps organize the Austin PHP user group and the ATX Web Lunch, the latter of which is basically an excuse to grab tasty tacos while talking tech a few times per month.<br /><br />

                <a href="/talks#dependency-injection-for-mere-humans" title="Talk: Dependency Injection for Mere Humans">Talk: Dependency Injection for Mere Humans</a><br /><br />
            </div>
        </div>

        <div id="jacob-mather" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#jacob-mather" title="Jacob Mather"><img src="/img/speakers/jacob_mather.jpg" alt="Jacob Mather" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Jacob Mather</h2>

                <strong>Bio:</strong> Jacob Mather has been working with distributed software systems for over 25 years. With a focus on quality software design and end user experience, he loves working with others to build great software that people want to use.<br /><br />

                <a href="/talks#promises-and-queues-using-unlikely-suspects-to-handle-asynchronous-parallel-processing" title="Talk: Promises and Queues: Using Unlikely Suspects to Handle Asynchronous Parallel Processing">Talk: Promises and Queues: Using Unlikely Suspects to Handle Asynchronous Parallel Processing</a><br /><br />
            </div>
        </div>

        <div id="jason-mccreary" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#jason-mccreary" title="Jason McCreary"><img src="/img/speakers/jason_mccreary.jpg" alt="Jason McCreary" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Jason McCreary</h2>

                <strong>Bio:</strong> Jason McCreary, or JMac, has been writing code for over two decades. He shares his experiences through speaking, coaching, and organizing local meetups. He's the creator of Laravel Shift. JMac considers himself an "active geek" - with a passion for programming & the great outdoors.<br /><br />

                <a href="/talks#php-plus-nginx-plus-redis-equals-ludicrous-speed" title="Talk: PHP + nginx + Redis = Ludicrous Speed">Talk: PHP + nginx + Redis = Ludicrous Speed</a><br /><br />

                <a href="/tutorials#start-testing-your-php-code" title="Tutorial: Start testing your PHP code">Tutorial: Start testing your PHP code</a><br /><br />
            </div>
        </div>

        <div id="jeremy-mikola" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#jeremy-mikola" title="Jeremy Mikola"><img src="/img/speakers/jeremy_mikola.jpg" alt="Jeremy Mikola" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Jeremy Mikola</h2>

                <strong>Bio:</strong> Jeremy Mikola is a software engineer at MongoDB's NYC office, where he helps develop the PHP driver. He is also a contributor to various OSS projects in the Symfony and Doctrine eco-systems. Jeremy lives in Hoboken, NJ and is known to enjoy a good sandwich.<br /><br />

                <a href="/talks#php-internals-for-the-inquisitive-developer" title="Talk: PHP Internals for the Inquisitive Developer">Talk: PHP Internals for the Inquisitive Developer</a><br /><br />
            </div>
        </div>

        <div id="josh-holmes" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#josh-holmes" title="Josh Holmes"><img src="/img/speakers/josh_holmes.jpg" alt="Josh Holmes" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Josh Holmes</h2>

                <strong>Bio:</strong> Josh Holmes is a passionate soul who gets his kicks solving problems with deep fried awesomeness. He is currently employed by Microsoft as the lead of the Web Apps and Frameworks team helping build a better browser for people to build apps around. Prior to joining Microsoft in October 2006, Josh was a consultant working with a variety of clients ranging from large Fortune 500 firms to smaller sized companies. Josh is a frequent speaker and lead panelist at national and international software development conferences focusing on web technologies on the Microsoft stack such as ASP.NET, PHP, IronRuby, JavaScript and more. Community focused, Josh has founded and/or run many technology organizations from the Great Lakes Area .NET Users Group to the Ann Arbor Computer Society and was on the forming committee for CodeMash. You can contact Josh through his blog at https://joshholmes.com.<br /><br />

                <a href="/talks#performance-tuning-your-progressive-web-app-pwa" title="Talk: Performance Tuning Your Progressive Web App (PWA)">Talk: Performance Tuning Your Progressive Web App (PWA)</a><br /><br />
            </div>
        </div>

        <div id="kat-zien" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#kat-zien" title="Kat Zień"><img src="/img/speakers/kat_zien.jpg" alt="Kat Zień" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Kat Zień</h2>

                <strong>Bio:</strong> Writing Go and PHP at Brightpearl. Working remotely from Bristol, UK or anywhere with wifi. Her main interests include automating #allthethings, sorting out legacy code and making things simpler and faster. She's co-organising and giving talks at PHPSW and Golang Bristol++. Kat loves travelling and keeping active, appreciates good coffee and is a big Lego fan. She cycles across Europe with TechBikers to raise money for Room To Read.<br /><br />

                <a href="/talks#performance-optimisation-how-do-i-go-about-it" title="Talk: Performance optimisation: how do I go about it?">Talk: Performance optimisation: how do I go about it?</a><br /><br />
            </div>
        </div>

        <div id="kathy-forte" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#kathy-forte" title="Kathy Forte"><img src="/img/speakers/kathy_forte.jpg" alt="Kathy Forte" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Kathy Forte</h2>

                <strong>Bio:</strong> Kathy Forte is a Solutions Architect for the MySQL division within Oracle where she is working with cloud technology, distributed databases, Docker and the MySQL server. She has been working in the relational databases realm for over twenty years as a developer, trainer, sales engineer, and technical manager. She previously worked at ParAccel as a part of a team that developed the massive parallel columnar database that is the foundation of Amazon Redshift, a cloud-based data warehouse.<br /><br />

                <a href="/talks#driving-innovation-with-mysql-8-and-docker" title="Talk: Driving Innovation with MySQL 8.0 and Docker">Talk: Driving Innovation with MySQL 8.0 and Docker</a><br /><br />
            </div>
        </div>

        <div id="korvin-szanto" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#korvin-szanto" title="Korvin Szanto"><img src="/img/speakers/korvin_szanto.jpg" alt="Korvin Szanto" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Korvin Szanto</h2>

                <strong>Bio:</strong> PHP developer from Portland with a passion for programming, community, and open source.<br /><br />

                <a href="/talks#applying-solid-and-supercharging-your-testing-suite" title="Talk: Applying SOLID and supercharging your testing suite">Talk: Applying SOLID and supercharging your testing suite</a><br /><br />
            </div>
        </div>

        <div id="lisa-bock" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#lisa-bock" title="Lisa Bock"><img src="/img/speakers/lisa_bock.jpg" alt="Lisa Bock" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Lisa Bock</h2>

                <strong>Bio:</strong> Lisa Bock is an associate professor in the Information Technology department at Pennsylvania College of Technology, in Williamsport, PA. Since 2004, she has been teaching everything from forensics to network security that include: networking, security, biometrics, technical support, protocol vulnerabilities (using Wireshark), cryptography, CCNA Security, CCNA Cyberops and VoIP and Unified Communications. She holds an MS from University of Maryland University College, along with numerous other certifications. She has had training in programming, forensics, networking, steganography, and network security. She is involved with various volunteer activities, has evaluated professional journals, published 27 courses on Lynda.com, and is an award-winning speaker. Lisa and her husband Mike enjoy bike riding, watching movies, and traveling.<br /><br />

                <a href="/talks#essentials-of-blockchain-technology" title="Talk: Essentials of blockchain technology">Talk: Essentials of blockchain technology</a><br /><br />
            </div>
        </div>

        <div id="lorna-mitchell" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#lorna-mitchell" title="Lorna Mitchell"><img src="/img/speakers/lorna_mitchell.jpg" alt="Lorna Mitchell" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Lorna Mitchell</h2>

                <strong>Bio:</strong> Lorna is based in Yorkshire; she is a Developer Advocate with Nexmo as well as a published author and experienced conference speaker. She brings her technical expertise on a range of topics to audiences all over the world with her writing and speaking engagements, always delivered with a very practical slant. In her spare time, Lorna blogs at http://lornajane.net.<br /><br />

                <a href="/talks#working-with-webhooks" title="Talk: Working with Webhooks">Talk: Working with Webhooks</a><br /><br />
            </div>
        </div>

        <div id="matt-trask" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#matt-trask" title="Matt Trask"><img src="/img/speakers/matt_trask.jpg" alt="Matt Trask" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Matt Trask</h2>

                <strong>Bio:</strong> Matt is an open source developer with a passion for clean code, API's and dinosaurs. Not old, fossilized code, just raptors and t-rexs. Besides being active with mentoring and co-organizing NashAPIs, Matt looks for new craft beers to try as well drinking too much coffee. When he isn't working on APIs, he can be found antagonizing cars on his bicycle.<br /><br />

                <a href="/talks#get-started-with-Vuejs" title="Talk: Get started with Vue.js">Talk: Get started with Vue.js</a><br /><br />
            </div>
        </div>

        <div id="michael-moussa" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#michael-moussa" title="Michael Moussa"><img src="/img/speakers/michael_moussa.jpg" alt="Michael Moussa" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Michael Moussa</h2>

                <strong>Bio:</strong> Michael has over 18 years experience with all aspects of building and maintaining PHP applications. He is currently working as a Product Architect on Rackspace's Managed Public Cloud team. In his spare time, he enjoys homebrewing his award-winning beer, cycling, and trying to find less expensive hobbies.<br /><br />

                <a href="/talks#ci-cd-for-php-on-aws" title="Talk: CI/CD for PHP on AWS">Talk: CI/CD for PHP on AWS</a><br /><br />
            </div>
        </div>

        <div id="mike-stowe" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#mike-stowe" title="Mike Stowe"><img src="/img/speakers/mike_stowe.jpg" alt="Mike Stowe" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Michael Stowe</h2>

                <strong>Bio:</strong> Author of Undisturbed REST, Michael Stowe has spoken at conferences around the world. An active advocate for creating better architectures and interfaces, his work has also been featured on ProgrammableWeb, DZone, and InfoQ. You can view his past talks and slides at http://www.mikestowe.com/slides and follow him on Twitter @mikegstowe.<br /><br />

                <a href="/talks#call-text-video-me-maybe" title="Talk: Call... Text... Video Me Maybe?">Talk: Call... Text... Video Me Maybe?</a><br /><br />

                <a href="/tutorials#rest-api-workshop" title="Tutorial: REST API Workshop">Tutorial: REST API Workshop</a><br /><br />
            </div>
        </div>

        <div id="miro-svrtan" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#miro-svrtan" title="Miro Svrtan"><img src="/img/speakers/miro_svrtan.png" alt="Miro Svrtan" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Miro Svrtan</h2>

                <strong>Bio:</strong> Started using PHP as a student, back in 1999. At first he worked as a one man band web developer and from there he progressed, via focusing on PHP development in a team environment, to be a senior dev, tech lead &amp; technical analyst.
                He found much more happiness doing backend stuff so focuses on scalable backends and devops tasks this days.<br /><br />

                <a href="/talks#year-with-event-sourcing-and-cqrs" title="Talk: Year with event sourcing and CQRS">Talk: Year with event sourcing and CQRS</a><br /><br />
            </div>
        </div>

        <div id="nara-kasbergen" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#nara-kasbergen" title="Nara Kasbergen"><img src="/img/speakers/nara_kasbergen.jpg" alt="Nara Kasbergen" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Nara Kasbergen</h2>

                <strong>Bio:</strong> Nara Kasbergen is a senior full-stack developer in NPR (National Public Radio)’s Digital Media group, where she's worked on a variety of projects, including the NPR Music homepage redesign and the third-party developer platform for NPR One. She is currently part of a small skunkworks team building custom applications for voice UI platforms such as Amazon Alexa and Google Home. She is passionate about Developer Experience (DX), community-building, the intersection of humans and code, and her volunteer work for Open Sourcing Mental Illness, a non-profit organization raising awareness about mental health in the tech industry.<br /><br />

                Though she has no noticeable accent, she hails from The Netherlands and lived in Munich, Houston, Pittsburgh, Tokyo, and New York City prior to settling down in Washington, DC. In her spare time, she satisfies her foodie habits by trying out all of the best restaurants in the city, collects board games, and watches too much Netflix.<br /><br />

                <a href="/keynotes#welcome-to-the-php-community" title="General Session: Welcome to the PHP community">General Session: Welcome to the PHP community</a><br /><br />
            </div>
        </div>

        <div id="olivia-liddell" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#olivia-liddell" title="Olivia Liddell"><img src="/img/speakers/olivia_liddell.jpg" alt="Olivia Liddell" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Olivia Liddell</h2>

                <strong>Bio:</strong> Olivia Liddell is a Cloud Training Specialist at Cloudbakers. She is a former Chicago Public Schools teacher who now specializes in technology training and change management. She is passionate about teaching, mentoring, and distance running.<br /><br />

                <a href="/keynotes#think-like-a-trainer-strategies-for-improving-your-communication-skills" title="General Session: Think Like a Trainer: Strategies for Improving Your Communication Skills">General Session: Think Like a Trainer: Strategies for Improving Your Communication Skills</a><br /><br />
            </div>
        </div>

        <div id="perside-foster" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#perside-foster" title="Perside Foster"><img src="/img/speakers/perside_foster.jpg" alt="Perside Foster" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Perside Foster</h2>

                <strong>Bio:</strong> Partners Solutions Architect, MySQL Sales Consulting at Oracle. Experienced Developer with a demonstrated history of working in the information technology and services industry. Skilled in Requirements Analysis, Oracle Database, Enterprise Software, Agile Methodologies, and Databases<br /><br />

                <a href="/talks#php-and-the-internet-of-things-iot" title="Talk: PHP and the Internet of Things(IoT)">Talk: PHP and the Internet of Things(IoT)</a><br /><br />
            </div>
        </div>

        <div id="pj-hagerty" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#pj-hagerty" title="PJ Hagerty"><img src="/img/speakers/pj_hagerty.png" alt="PJ Hagerty" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>PJ Hagerty</h2>

                <strong>Bio:</strong> Developer, writer, speaker, musician, and Developer Advocate, PJ is known to travel the world speaking about programming and the way people think and interact. He is also known for wearing hats.<br /><br />

                <a href="/keynotes#pop-songs-and-programming-for-fun-and-profit" title="Keynote: Pop Songs and Programming for Fun and Profit">Keynote: Pop Songs and Programming for Fun and Profit</a><br /><br />
            </div>
        </div>

        <div id="rob-allen" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#rob-allen" title="Rob Allen"><img src="/img/speakers/rob_allen.jpg" alt="Rob Allen" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Rob Allen</h2>

                <strong>Bio:</strong> Rob Allen is a software consultant and developer with many years experience and writes code in PHP and other interesting languages. He is part of Slim Framework's leadership team and contributes to Apache OpenWhisk and other open source projects. Rob is a published author and based in the UK where he runs Nineteen Feet Limited, focussing on API development, training and consultancy. In his spare time, Rob blogs at akrabat.com and can often be seen with a camera in his hand.<br /><br />

                <a href="/talks#introduction-to-serverless-php" title="Talk: Introduction to Serverless PHP">Talk: Introduction to Serverless PHP</a><br /><br />
            </div>
        </div>

        <div id="terry-chay" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#terry-chay" title="Terry Chay"><img src="/img/speakers/terry_chay.jpg" alt="Terry Chay" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Terry Chay</h2>

                <strong>Bio:</strong> If Zend puts your picture on a deck of cards, you've either arrived in the PHP world or are a terrorist. Terry Chay is a PHP Terrorist. In previous lives he was Director of Features Engineering at the Wikimedia Foundation (Wikipedia), the "planet taker" for Automattic (WordPress) architected the third largest social network in the U.S. in PHP, developed the largest revenue-generating product in PHP for Plaxo (now Comcast) as their first web engineer, programmed the communication layer between an internet-enabled home control device and the web browser, voice portals, PDAs and cell phones via SOAP and XMLRPC in PHP, and built the first travel search engine in… (surprise) PHP! He has been known to give seminars in PHP development, which is really just a veiled excuse to play with Keynote and allow the listeners to meme him with a #tcfc and new "chayisms."<br /><br />

                <a href="/talks#the-recommendation-engine-a-case-study-on-an-application-of-a-recommender-system" title="Talk: The Recommendation Engine: A case study on an application of a recommender system">Talk: The Recommendation Engine: A case study on an application of a recommender system</a><br /><br />
            </div>
        </div>

        <div id="tim-bond" class="clearfix">
            <hr />

            <div class="span3" style="height:225px; width:225px;">
                <a href="/speakers#tim-bond" title="Tim Bond"><img src="/img/speakers/tim_bond.jpg" alt="Tim Bond" /></a>
            </div>
            <div class="span5" style="text-align: justify;">
                <h2>Tim Bond</h2>

                <strong>Bio:</strong> Tim is a senior full stack PHP developer that has been working with PHP for 14 years and has seen PHP grow from its hodgepodged roots to a modern development language. When not in front of a computer, you'll probably find him hiking or biking around beautiful Seattle, or putting together a new Lego set on one of the rare rainy days.<br /><br />

                <a href="/talks#xdebug-will-forever-change-the-way-you-debug-your-php-code" title="Talk: Xdebug will forever change the way you debug your PHP code">Talk: Xdebug will forever change the way you debug your PHP code</a><br /><br />
            </div>
        </div>

    </div>
    <hr />
</div>