<div class="page-header">
    <h1>Talks</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        Below is a full listing of 50 minute talks to be presented at SunshinePHP. Our selection committee did a wonderful job of selecting a nice variety of talk topics by some of the best speakers.  We hope there is something for everyone developing with PHP.<br /><br />
    
        NOTE: Attending these 50 minute talks on Friday and Saturday February 3rd and 4th requires the purchase of a normal conference ticket on the <a href="http://sunshinephp.com/register" title="Speaker: SunshinePHP Registration">Registration page</a>.
    </p>
    
    <div style="padding-left: 30px;">

        <div id="a-common-taxonomy-of-bugs-and-how-to-squash-them" style="text-align: justify;">
            <hr />
        
            <h2>A Common Taxonomy of Bugs and How to Squash Them</h2>
        
            <a href="/speakers#kylie-stradley" title="Speaker: Kylie Stradley">Kylie Stradley</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large development">Development</div>

            <br /><br />

            Catching software bugs is a mysterious magic, unknowable by science and untouchable by process.<br /><br />

            False! Programming bugs, like real bugs, can be organized into a taxonomy. Come with me and I'll show you how classification can help you build “programmer’s instinct” into a logical debugging process.<br /><br />

            Debugging may be instinctual but those instincts come from seeing, identifying and diagnosing patterns. In this talk, we’ll use phenetic taxonomy to build a debugging decision making network based on attributes and behaviors of common bugs. Newer developers will learn how to apply systematic pattern matching to debugging while seasoned developers will learn how to use their instincts to teach debugging.<br /><br />
        </div>

        <div id="amp-your-website-an-introduction-to-accelerated-mobile-pages" style="text-align: justify;">
            <hr />

            <h2>AMP your website: An Introduction to Accelerated Mobile Pages</h2>

            <a href="/speakers#robert-mcfrazier" title="Speaker: Robert McFrazier">Robert McFrazier</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large mobile">Mobile</div>

            <br /><br />

            The Accelerated Mobile Page project aims to create a framework that allows webpages to load fast on mobile devices. By focusing on things that browsers do fast, and avoiding things that take time, the AMP project allows mobile devices to load content almost instantly. During this presentation we will dive into AMP HTML, AMP JS and the Google AMP cache. We will look at the AMP open source project and its closed source alternatives and we will also see how HTTP/2 plays into making your mobile site load faster. We will also look at how you can monetize your AMP based site.<br /><br />
        </div>
        
        <div id="baby-steps-giant-leaps-xdebug-for-beginners" style="text-align: justify;">
            <hr />

            <h2>Baby Steps -> Giant Leaps. (Xdebug for beginners)</h2>

            <a href="/speakers#sean-prunka" title="Speaker: Sean Prunka">Sean Prunka</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large development">Development</div>

            <br /><br />

            var_dump($foo)<br /><br />

            print_r($bar)<br /><br />

            die($baz)<br /><br />

            Are these your current debugging tools? Wouldn't it be nice to see $foo, $bar, and $baz while the code is still being executed? Watch it change, live? And not have it just dumped all over the output of your otherwise beautiful app? We'll install XDebug, set up your IDE to use it (with examples shown for PhpStorm, Netbeans, and ZendStudio), then we'll actually walk through some badly written code that needs to be debugged.<br /><br />
        </div>

        <div id="building-great-admin-panels-with-symfony-and-sonataadminbundle" style="text-align: justify;">
            <hr />

            <h2>Building great admin panels with Symfony and SonataAdminBundle</h2>

            <a href="/speakers#victoria-quirante" title="Speaker: Victoria Quirante">Victoria Quirante</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large framework">framework</div>&nbsp;<div class="tag large symfony">Symfony</div>

            <br /><br />

            Coding an admin panel is not the problem you love to face when you wake up in the morning, but is something you need to do very often. Having an environment that allows you to implement this efficiently, is something key for a developer. Symfony and SonataAdminBundle provide a way to do it that gives you as many out-of-the-box functionalities as you could dream of, plus the chance to customize every piece -if you know how to do it. The purpose of this talk is to show how easily can you get profit of SonataAdminBundle once you know how to deal with it.<br /><br />

            We will start with a clean installation of Symfony and SonataAdminBundle, showing how to build up form there, and how to solve the main problems and questions that you usually face when having a complex admin panel in your hands. The main purposes are to show how to use SonataAdminBundle in the most standard way, and how to build up from that point, customizing whatever you need to meet the exact requirements of the project.<br /><br />
        </div>

        <div id="code-coverage-for-security-in-application-migrations" style="text-align: justify;">
            <hr />

            <h2>Code Coverage for Security in Application Migrations</h2>

            <a href="/speakers#dana-luther" title="Speaker: Dana Luther">Dana Luther</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large testing">Testing</div>

            <br /><br />

            So the time has come to take the leap and upgrade your application to a new major version of the underlying framework, or, perhaps, to an entirely different framework... how do you ensure that none of your functionality or usability is impacted by a potentially drastic rewrite of the underlying systems? How can you move forward with 100% confidence in your migrated codebase? Testing, testing and more testing. Using a combination of unit, functional and acceptance tests can give you the certainty you need. In this talk, we will go over key strategies for ensuring that you begin with full code coverage and move forward with confidence.<br /><br />

            Testing framework: Codeception 2.2.x <br /><br />
        </div>

        <div id="composing-php-applications-with-middleware" style="text-align: justify;">
            <hr />

            <h2>Composing PHP Applications with Middleware</h2>

            <a href="/speakers#josh-butts" title="Speaker: Josh Butts">Josh Butts</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large development">Development</div>

            <br /><br />

            With the advent of the PSR-7 standard, middleware has become a household name in the PHP ecosystem. This talk will cover middleware architecture concepts including a comparison of how middleware is being used in PHP versus other languages. We’ll look at how to leverage middleware concepts to build applications from scratch as well as combine off-the-shelf components using middleware as the glue. Of course, we’ll also look at some downright dirty tricks you that middleware lets you get away with as well!<br /><br />
        </div>

        <div id="console-applications-automate-your-life-away" style="text-align: justify;">
            <hr />

            <h2>Console Applications: Automate your life away</h2>

            <a href="/speakers#matt-trask" title="Speaker: Matt Trask">Matt Trask</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large development">Development</div>

            <br /><br />

            Today, there is a huge focus on frameworks, web applications and micro services. As we focus on those, we look past something simple, a command line script that can take tasks and remove them from your plate. From something simple like exporting a database back up to sending out notifications to users via an API, a command line script can remove hours of work, and just sit in the background until called via cron or an action. Lets look at ways to automate your code, both production and tests and what libraries can help us write awesome CLI scripts!<br /><br />
        </div>

        <div id="containing-chaos-with-kubernetes" style="text-align: justify;">
            <hr />

            <h2>Containing Chaos with Kubernetes</h2>

            <a href="/speakers#terrence-ryan" title="Speaker: Terrence Ryan">Terrence Ryan</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large devops">DevOps</div>

            <br /><br />

            Okay, you've made the move to containers and can now write Dockerfiles for everything. How do you manage all of those containers?. Have you found that you traded managing individual machines for managing individual containers?<br /><br />

            Kubernetes, an Open Source container orchestration engine, can be your answer. We'll explore Kubernetes and see how you can use it to run massive collections of containers that fix their own problems and allow you to move your setup wherever you need to be. <br /><br />
        </div>

        <div id="control-your-application-with-your-brain" style="text-align: justify;">
            <hr />

            <h2>Control your application with your brain</h2>

            <a href="/speakers#ibis-arrastia" title="Speaker: Ibis Arrastia">Ibis Arrastia</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large uiux">UIUX</div>

            <br /><br />

            See the latest technology in brain computer interfaces and see a live demo of how you can control your applications with just your mind! As we seek better user interfaces, maybe future applications will no longer require a mouse and a keyboard, just your thoughts.<br /><br />
        </div>

        <div id="data-visualization-with-d3" style="text-align: justify;">
            <hr />

            <h2>Data Visualization with D3</h2>

            <a href="/speakers#wenting-zhao" title="Speaker: Wenting Zhao">Wenting Zhao</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large javascript">Javascript</div>

            <br /><br />

            Introduction/Tutorial of Data Visualization in JavaScript, with the use of the D3.js library.<br /><br />
        </div>

        <div id="debugging-effectively" style="text-align: justify;">
            <hr />

            <h2>Debugging Effectively</h2>

            <a href="/speakers#colin-odell" title="Speaker: Colin O'Dell">Colin O'Dell</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large development">Development</div>

            <br /><br />

            Software bugs are inevitable; some are especially difficult to track down, causing you to waste countless hours before throwing your hands up in defeat. It doesn't have to be this way! The mental fatigue and wasted time can be avoided by using strategies like identifying the most-appropriate tool, taking a logical &amp; objective approach, challenging assumptions, listening to variables, isolating the code path, and reinforcing code with automated tests. Attendees will learn how to combine these techniques with the right mindset and attitude in order to debug their code quickly and effectively.<br /><br />
        </div>

        <div id="design-for-developers" style="text-align: justify;">
            <hr />

            <h2>Design for Developers</h2>

            <a href="/speakers#kevin-and-cathy-bruce" title="Speaker: Kevin and Cathy Bruce">Kevin and Cathy Bruce</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large development">Development</div>&nbsp;<div class="tag large uiux">UIUX</div>

            <br /><br />

            While there is some truth to “some amount of innate talent is required to be a true artist”, it’s not necessarily so in learning how to design. And as developers, we’ve all found ourselves struggling when called on to be both the designer and developer of a website. There are processes and techniques you can use to create a well designed site. From “hierarchy of content” to “font usage” to “proximity of elements”, I will teach you how to develop an eye for design that will carry you through any task, and may even alter how you see the world as you learn related patterns are everywhere.<br /><br />
        </div>

        <div id="develop-a-security-mindset" style="text-align: justify;">
            <hr />

            <h2>Develop A Security Mindset</h2>

            <a href="/speakers#lisa-bock" title="Speaker: Lisa Bock">Lisa Bock</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large security">Security</div>

            <br /><br />

            Today, cyber threats are everywhere, and are becoming more aggressive, complex and sophisticated. An attack can result in theft of information, exposure to sensitive information. A threat is something we cannot prevent, such as the threat of someone trying to launch a Cross Site Scripting Attack (XSS). However, we can reduce the risk by ensuring proper input validation on all data stored in the database.<br /><br />

            Web based applications represent an attack vector. As a developer, you should be aware of the most important security concerns when you develop your web interface, and the best practices you can take keep your servers, software, and data safe from threats that exist in today’s complex environment. I’ll provide an overview of security, list some of the top vulnerabilities, and get participants into a security mind set.<br /><br />
        </div>

        <div id="devops-for-small-teams" style="text-align: justify;">
            <hr />

            <h2>DevOps For Small Teams</h2>

            <a href="/speakers#joe-ferguson" title="Speaker: Joe Ferguson">Joe Ferguson</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large devops">DevOps</div>

            <br /><br />

            Do your peers come to you when they need help with networking?<br />
            Are the the one that has to trace down problems with local networking resources?<br />
            Do you know the server is down because your Slack DMs blow up?<br /><br />

            If you answer yes to any of these, congratulations, you are "DevOps". Every company has DevOps people, whether they call them that or not. These are the people that fix things, patch software, that help developers stay focused on developing.<br /><br />

            In this session I will share with you lessons learned form 9+ years of being "the server person". We will cover topics like:<br />
            - Stop using WAMP/MAMP and start using Vagrant<br />
            - Version control isn't renaming files<br />
            - Automate common tasks with shell scripts / command line PHP apps<br />
            - From Vagrant to Production<br /><br />

            Join me. Embrace your inner DevOps<br /><br />
        </div>

        <div id="dockerize-your-unit-tests-for-faster-feedback" style="text-align: justify;">
            <hr />

            <h2>Dockerize your unit tests for faster feedback</h2>

            <a href="/speakers#michelangelo-van-dam" title="Speaker: Michelangelo van Dam">Michelangelo van Dam</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large advanced">Adv</div>&nbsp;<div class="tag large devops">DevOps</div>&nbsp;<div class="tag large testing">Testing</div>

            <br /><br />

            Ever got the message "Fatal error: Out of memory" when running your unit tests? Or do you have to wait for more than 5 minutes for all of your unit tests to complete? We're using Docker to mitigate these and other issues. In this session I will show you how we have split up a single testsuite of 3K+ tests into manageable unit modules which are executed by Docker micro instances in parallel. And with this set up we test our application on the current PHP version, but it also allows us to test against a new major PHP version the moment it is released or even is available in beta.<br /><br />
        </div>

        <div id="dont-work-for-phpcs-make-phpcs-work-for-you" style="text-align: justify;">
            <hr />

            <h2>Don't work for PHPCS, make PHPCS work for you</h2>

            <a href="/speakers#juliette-reinders-folmer" title="Speaker: Juliette Reinders Folmer">Juliette Reinders Folmer</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large development">Development</div>

            <br /><br />

            Congratulations! Your team has chosen a coding standard to use and you're well on your way to a consistent code style for all your projects. But... there are some extra things you'd like to check for, some rules you really can't be bothered with and some which sort of fit your needs, but not completely. Now what?<br /><br />

            Come and learn how to make the PHP Codesniffer work for you and how to streamline the PHPCS related work-flow along the way.<br /><br />
        </div>

        <div id="employing-cqrs-and-event-sourcing-to-build-an-mvp" style="text-align: justify;">
            <hr />

            <h2>Employing CQRS and Event Sourcing to Build an MVP</h2>

            <a href="/speakers#beau-simensen" title="Speaker: Beau Simensen">Beau Simensen</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large development">Development</div>

            <br /><br />

            Learning about Command Query Responsibility Segregation (CQRS) and Event Sourcing can be both exciting and confusing. It sounds great, but how does it work in the real world? Won't it be a lot of work before you even get started? Will it be worth the investment and when will that investment start paying off? Are these technologies appropriate for building a minimum viable product (MVP)? Find out how these questions were answered for one team as they set out to build their MVP.<br /><br />
        </div>

        <div id="engineering-mastering-the-art-of-software" style="text-align: justify;">
            <hr />

            <h2>Engineering - Mastering the art of Software</h2>

            <a href="/speakers#cristiano-diniz-da-silva" title="Speaker: Cristiano Diniz da Silva">Cristiano Diniz da Silva</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large softskills">Soft-Skills</div>

            <br /><br />

            Software development has grown in the last 10 years, and with it the profession has also grown.<br /><br />

            This talk will cover the basic principles and mindset that differ from a software developer to a software engineer. Principles such as troubleshooting, toolsets, risk management, etc.<br /><br />

            The idea of the talk is to go over these base core principles and expose them to software developers starting in the profession or want to give a shift in their career improving it.<br /><br />
        </div>

        <div id="from-docker-to-production" style="text-align: justify;">
            <hr />

            <h2>From Docker to Production</h2>

            <a href="/speakers#chris-tankersley" title="Speaker: Chris Tankersley">Chris Tankersley</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large devops">DevOps</div>

            <br /><br />

            Congrats! You and your coworkers love Docker. Docker has become an increasingly helpful tool when it comes to devops. We can now build smaller, more robust local development setups with the promise of mirroring production. One thing that still plagues many situations is how to get those containers into production and update them over time. We will explore different tools for setting up, configuring, and maintaining containers as they go live.<br /><br />
        </div>

        <div id="going-password-free" style="text-align: justify;">
            <hr />

            <h2>Going Password-Free</h2>

            <a href="/speakers#eric-mann" title="Speaker: Eric Mann">Eric Mann</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large development">Development</div>&nbsp;<div class="tag large security">Security</div>

            <br /><br />

            Should a password be long and complex? What about a string of easy-to-remember words instead? Are password managers the best way forward? What about multiple factors? Is there a better way?<br /><br />

            These are all questions your users have: learn how to answer them and how to make security easy by moving beyond passwords for your web app entirely with magic link based authentication! Your users just click a link; they don't have to remember anything.<br /><br />
        </div>

        <div id="graph-databases-will-change-your-freakin-life" style="text-align: justify;">
            <hr />

            <h2>Graph Databases Will Change Your Freakin Life</h2>

            <a href="/speakers#edward-finkler" title="Speaker: Edward Finkler">Edward Finkler</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large database">Database</div>

            <br /><br />

            All of us have worked with relational DBs like MySQL or PostgreSQL, but for many use cases they aren't the best option. Graph databases have a simpler, more powerful model for handling complex related data. In this talk we'll work with Neo4j to explore the advantages of graph DBs. Attendees will learn the graph model, how graph DBs let you do things that are practically impossible with SQL, and the best options for integrating one into your PHP application -- new or existing.<br /><br />
        </div>

        <div id="http2-and-asynchronous-apis" style="text-align: justify;">
            <hr />

            <h2>HTTP/2 and Asynchronous APIs</h2>

            <a href="/speakers#davey-shafik" title="Speaker: Davey Shafik">Davey Shafik</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large api">API</div>&nbsp;<div class="tag large async">Async</div>

            <br /><br />

            HTTP/2 (H2) is coming, and along with it a whole new way of communicating over the web. Connection re-use, prioritization, multiplexing, and server push are just some of the features in H2.<br /><br />

            In this talk we'll look at the HTTP/2 protocol, and at how we can use asynchronous request now with HTTP/1.x. We will also look at what asynchronous requests and H2 mean for your API and clients in the future.<br /><br />
        </div>

        <div id="irresistible-apis" style="text-align: justify;">
            <hr />

            <h2>Irresistible APIs</h2>

            <a href="/speakers#kirsten-hunter" title="Speaker: Kirsten Hunter">Kirsten Hunter</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large api">API</div>

            <br /><br />

            When creating a new REST platform, the planning process frequently gets skipped (or is misunderstood) resulting in an ill-conceived API. I’ll walk you through the steps needed to create an API that developers love, and point out the common traps to avoid.<br /><br />

            The presentation will cover creating user stories, deciding on metrics, planning the API, design decisions, documentation and developer support. I will focus on creating a developer experience that will delight and amaze your developer partners and increase engagement with your platform. This talk will focus on higher level choices rather than HTTP architecture, and is appropriate for developers, product managers, or anyone else with an interest in achieving success for their API program.<br /><br />

            The Open API Ecosystem is an amazing opportunity for companies to partner with developers, but you really only get one chance to impress, so come learn how to make your company’s API an “A List” destination.<br /><br />
        </div>

        <div id="irritating-strings-iterating-things" style="text-align: justify;">
            <hr />

            <h2>Irritating Strings -- Iterating Things</h2>

            <a href="/speakers#eric-poe" title="Speaker: Eric Poe">Eric Poe</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large development">Development</div>

            <br /><br />

            Arrays are beautiful in PHP. One can map them, reduce them, filter them, foreach them, and use them in generators. Strings, on the other hand, are mere shadows to the Array. One can, uh, input and output Strings, and, when brave, manipulate them. What makes Arrays so awesome and Strings so dull? Iterators.<br /><br />

            In this talk, we’ll look at the modest origins of the String and the basics of the Iterator. Then, we’ll look at how we can make the String as awesome as the Array through the use of iterator interfaces.<br /><br />

            By the end of this talk, you will know the origins of the PHP String and you will be able to extend your knowledge of iterating through a String to be able to iterate through customized objects.<br /><br />
        </div>

        <div id="kicking-off-with-zend-expressive-and-doctrine-orm" style="text-align: justify;">
            <hr />

            <h2>Kicking off with Zend Expressive and Doctrine ORM</h2>

            <a href="/speakers#james-titcumb" title="Speaker: James Titcumb">James Titcumb</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large framework">Framework</div>&nbsp;<div class="tag large database">Database</div>&nbsp;<div class="tag large zendframework">Zend Framework</div>

            <br /><br />

            You've heard of Zend's new framework, Expressive, and you've heard it's the new hotness. In this talk, I will introduce the concepts of Expressive, how to bootstrap a simple application with the framework using best practices, and finally how to integrate a third party tool like Doctrine ORM. <br /><br />
        </div>

        <div id="locate-all-the-things" style="text-align: justify;">
            <hr />

            <h2>Locate all the things</h2>

            <a href="/speakers#derick-rethans" title="Speaker: Derick Rethans">Derick Rethans</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large database">Database</div>&nbsp;<div class="tag large search">Search</div>

            <br /><br />

            In this talk you will learn how to effectively store, retrieve and display geospatial data, such as roads, points of interests and more.<br /><br />

            First we will be importing an OpenStreetMap dataset covering London into MongoDB. This is not trivial due to the amount of data.<br /><br />

            After importing, we will look at which types of queries we can run to find things. Either by predicates, or with geospatial queries.<br /><br />

            And last we will have a look at how to display the data that we've requested, through a website using the Leaflet mapping library.<br /><br />
        </div>

        <div id="making-the-most-out-of-mysql" style="text-align: justify;">
            <hr />

            <h2>Making the most out of MySQL</h2>

            <a href="/speakers#gabriela-d-avila" title="Speaker: Gabriela D'Ávila">Gabriela D'Ávila</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large database">database</div>

            <br /><br />

            The new JSON fields are some of the most talking about new features in MySQL 5.7. But they are by no means the only awesome things this version has to offer. MySQL 5.7 is a year old, so this talk won't be an introduction to this version. We will be digging into 5.7 to see how to make the most of the tools available in it.

            Want to tackle important practical problem solving for your data, make your query performance analysis more efficient or look at how virtual columns can help you index data? This talk is for you!<br /><br />
        </div>

        <div id="meet-your-bff-building-backends-for-frontends" style="text-align: justify;">
            <hr />

            <h2>Meet your BFF - Building Backends-for-Frontends</h2>

            <a href="/speakers#luis-atencio" title="Speaker: Luis Atencio">Luis Atencio</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large api">API</div>&nbsp;<div class="tag large framework">Framework</div>

            <br /><br />

            We live in a highly distributed world. This means that data doesn’t all live in one place, development teams are scattered and spread geographically, and service modularization is the key to tackle the complexity of large enterprise systems—in short, the end of the monolith. As a result, modern distributed architectures (microservices) have become widespread. What does this mean for a professional PHP developer like you?<br /><br />

            It means that instead of reading data from your single, all-mighty MySQL server, you find yourself mashing up APIs from different sources that each make up a piece of the puzzle of the user interface your customers see. Unfortunately, this adds an incredible degree of difficulty to your code as the data is no longer accessible from your local, fast database, but from slower, remote, asynchronous RESTful APIs.<br /><br />

            In this talk , we explore the Reactive Extensions library for PHP (RxPHP), which will become your BFF when building a server-side aggregation endpoint that can compose data from multiple RESTful services or APIs and combine together in ways PHP developers have never seen before.<br /><br />
        </div>

        <div id="mysql-analysis-understanding-and-optimization-of-queries" style="text-align: justify;">
            <hr />

            <h2>MySQL: Analysis, understanding, and optimization of queries</h2>

            <a href="/speakers#michael-moussa" title="Speaker: Michael Moussa">Michael Moussa</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large database">Database</div>

            <br /><br />

            Your new database query ran quickly when you tested it, but seconds after deploying it, alarms are blaring and you’re scrambling to rollback before the site goes down. What happened?!?<br /><br />

            I can “EXPLAIN”.<br /><br />

            Queries that perform well under development load with limited datasets can easily bring a database to its knees under production load. In this talk, you will learn to decipher MySQL query execution plans, recognize portions that can be improved, and take the necessary steps to optimize your queries - all without starting any fires!<br /><br />
        </div>

        <div id="mysqls-json-data-type-n-document-store" style="text-align: justify;">
            <hr />

            <h2>MySQL's JSON Data Type &amp; Document Store</h2>

            <a href="/speakers#dave-stokes" title="Speaker: Dave Stokes">Dave Stokes</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large database">Database</div>

            <br /><br />

            MySQL now has a native JSON Data type. So like an Integer or a character, you can store an entire valid JSON document in a column of a table in a MySQL database. Sure you could store JSON data in a text field but then you end up using Regular Expressions to search that data and who needs that aggravation? This session will cover how JSON information is store in an optimized binary format, functions you need to know to use that JSON data (How many email fields are in that JSON document or how to update information), the usages of generated columns that take information from JSON documents to materialize a column that is indexed for searching, and lots of programming examples.<br /><br />

            Plus there is a new MySQL Protocol and X Devapi that allows you to use a MySQL database as a document store which means no writing queries, no structured query language, and the ability from your favorite programming language to do CRUD (Create, Replace, Update, Delete) directly.<br /><br />
        </div>

        <div id="not-on-calliday-on-call-best-practices" style="text-align: justify;">
            <hr />

            <h2>Not-On-Calliday: On-Call Best Practices</h2>

            <a href="/speakers#amanda-folson" title="Speaker: Amanda Folson">Amanda Folson</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large softskills">Soft-Skills</div>

            <br /><br />

            Being on call sucks, but it doesn’t have to. Many organizations struggle to maintain effective on-call rotations that minimize the number of people woken up in the middle of the night -- so much so, that “burnout syndrome” is an actual disorder that’s commonly experienced by professionals in on-call positions. In this talk, we’ll talk about how you can set up your on-call rotations to optimize the uptime of your infrastructure and your engineering team.<br /><br />
        </div>

        <div id="practical-performance-tips-and-tricks-to-make-your-html-javascript-faster" style="text-align: justify;">
            <hr />

            <h2>Practical Performance Tips and Tricks to Make Your HTML/JavaScript Faster</h2>

            <a href="/speakers#doris-chen" title="Speaker: Doris Chen">Doris Chen</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large javascript">Javascript</div>&nbsp;<div class="tag large scaling">Scaling</div>

            <br /><br />

            How to tackle real-world web platform performance problems in modern websites and apps? This session starts with a basic understanding of the web platform and then explores to a set of problem/solution pairs built from industry-standard performance guidance. In the talk, we will demonstrate performance tips and tricks that will help you improve the performance of your apps and sites today. We will discuss the following respond to network requests, speed and responsiveness, optimizing media usage, and writing fast JavaScript. These performance tips and tricks apply equally to web sites that run on standards based web browsers, as well as to modern apps.<br /><br />
        </div>

        <div id="pulling-up-your-legacy-app-by-its-bootstraps" style="text-align: justify;">
            <hr />

            <h2>Pulling up Your Legacy App by its Bootstraps!</h2>

            <a href="/speakers#emily-stamey" title="Speaker: Emily Stamey">Emily Stamey</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large development">Development</div>&nbsp;<div class="tag large oop">OOP</div>

            <br /><br />

            Your mission, should you choose to accept it, is to support an application built on an older framework. Refactoring isn't an easy option. The code is untested and nowhere near best practices or standards. In this session, we'll talk about strategies to incorporate modern PHP coding practices to add features and functionality and retiring the older code in pieces. We'll review specific examples and code from a real project where we bootstrapped a legacy application that needed a lot of help to become useful to its users and simpler for developers to maintain. We'll talk about strategies to leave the existing code in place until the new code is ready to replace it in whole or in pieces.<br /><br />
        </div>

        <div id="securing-legacy-applications" style="text-align: justify;">
            <hr />

            <h2>Securing Legacy Applications</h2>

            <a href="/speakers#chris-cornutt" title="Speaker: Chris Cornutt">Chris Cornutt</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large security">Security</div>

            <br /><br />

            It’s common to hear people preach “plan in security from the start” and in an ideal world you can. Here in the real world, though, we have legacy code that’s gathered over time and comes with a host of problems - (in)security included. What do you do when you’ve been commissioned with securing an application that’s showing its age? Follow along with me as a I step you through a list of tips and tricks you can use to discover security issues in your application and effectively fix them and secure your application.<br /><br />

            Topics will include some of the most common vulnerability types, key places to look for potential issues and arm you with the tools and knowledge you’ll need to refactor that legacy application into something secure.<br /><br />
        </div>

        <div id="tales-from-the-crypt-cryptography-primer" style="text-align: justify;">
            <hr />

            <h2>Tales from the Crypt: Cryptography Primer</h2>

            <a href="/speakers#adam-englander" title="Speaker: Adam Englander">Adam Englander</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large advanced">Adv</div>&nbsp;<div class="tag large security">security</div>

            <br /><br />

            Cryptography is a complex and confusing subject. There seems to be more disinformation than actual information. Learn how to properly use cryptography to secure user credentials and consumer data. We will discuss cryptographic methodologies and algorithms available to PHP. The main focus will focus be on encryption with RSA and AES and hashing with SHA and the PHP Password Hashing extension. We will discuss other methodologies as part of a compare and contrast based on cryptography strength and randomness. <br /><br />
        </div>

        <div id="taming-the-resource-tiger" style="text-align: justify;">
            <hr />

            <h2>Taming the Resource Tiger</h2>

            <a href="/speakers#elizabeth-m-smith" title="Speaker: Elizabeth M Smith">Elizabeth M Smith</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large development">Development</div>&nbsp;<div class="tag large scaling">Scaling</div>&nbsp;<div class="tag large devops">DevOps</div>

            <br /><br />

            No matter how many virtual machines you throw at a problem you always have the physical limitations of hardware. Memory, CPU, and even your NIC's throughput have finite limits. Are you trying to load that 5 GB csv into memory to process it? No really, you shouldn't!<br /><br />

            PHP has many built in features to deal with data in more efficient ways that pumping everything into an array or object. Using PHP stream and stream filtering mechanisms you can work with chunked data in an efficient matter, with sockets and processes you can farm out work efficiently and still keep track of what your application is doing. These features can help with memory, CPU, and other physical system limitations to help you scale without the giant AWS bill.<br /><br />
        </div>

        <div id="time-management-for-grumpy-programmers" style="text-align: justify;">
            <hr />

            <h2>Time Management For Grumpy Programmers</h2>

            <a href="/speakers#chris-hartjes" title="Speaker: Chris Hartjes">Chris Hartjes</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large softskills">SoftSkills</div>

            <br /><br />

            I don't have enough time" is a cry that echoes across social media and online chat rooms. Work deadlines, family obligations, hobbies that don't involve computers -- they all are taking out chunks of the time we have available to us. But there is one immutable fact --we all have the same amount of time available, some of us just find different ways to use it.<br /><br />

            In this session learn how long-time grumpy programmer Chris Hartjes organizes and makes decisions about how to spend his time. Business owner, involved work-from-home parent, conference speaker, podcaster, collectable card game enthusiast - Chris does this all and more without feeling super-stressed about it. Was he born with this super power? Not at all. The talk will cover how Chris plans his life, his preferred tools, and strategies for figuring out what to do and when to do it. It is possible to get a lot done and not become a workaholic in the process. Sit back, relax, and let a grumpy programmer show you how to maximize your time.<br /><br />
        </div>

        <div id="unit-testing-by-example" style="text-align: justify;">
            <hr />

            <h2>Unit Testing by Example</h2>

            <a href="/speakers#anna-filina" title="Speaker: Anna Filina">Anna Filina</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large testing">Testing</div>

            <br /><br />

            Everyone tells you that you need to test. You know the theory, but you don't know where to begin. What to test? What cases to write? Through realistic and pragmatic examples, this presentation will take you away from var_dump and ease you into the testing business until you're ready to do TDD. All this without losing sight of the tight deadlines.<br /><br />
        </div>

        <div id="web-performance-2017-myths-and-truths" style="text-align: justify;">
            <hr />

            <h2>Web Performance 2017: Myths and Truths</h2>

            <a href="/speakers#christian-wenz" title="Speaker: Christian Wenz">Christian Wenz</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large scaling">Scaling</div>

            <br /><br />

            The performance of a web site is one of the criteria used by Google and other search engines to determine the site's ranking. Various studies have shown that there is a link between performance and conversion rates. These are just two of many reasons to make performance optimization a mandatory step in your development process. However advice that was relevant a few years ago is often made obsolete by new browser versions or new technologies like HTTP/2.<br /><br />
            
            We will cover several aspects of optimizing a site from a performance perspective, debunk some myths, and also present tools that help analyzing a web site's performance.<br /><br />
        </div>

        <div id="websockets-and-event-driven-programming-with-reactphp" style="text-align: justify;">
            <hr />

            <h2>Websockets and Event-driven Programming with ReactPHP</h2>

            <a href="/speakers#steve-meyers" title="Speaker: Steve Meyers">Steve Meyers</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large intermediate">Int</div>&nbsp;<div class="tag large async">Async</div>&nbsp;<div class="tag large javascript">Javascript</div>

            <br /><br />

            Modern browsers support a new standard call Websockets, which allow persistent connections between a browser and a server. We'll discuss how to implement Websockets with your client-side Javascript talking to your server-side PHP, using the ReactPHP framework.<br /><br />
        </div>

        <hr />
    </div>
</div>