<div class="page-header">
    <h1>Talks</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        Below is a full listing of 60-minute talks to be presented at SunshinePHP. Our selection committee did a wonderful job of selecting a nice variety of talk topics by some of the best speakers.  We hope there is something for everyone developing with PHP.<br /><br />
    
        NOTE: Attending these 60-minute talks on Friday and Saturday February 8th and 9th requires the purchase of a normal conference ticket on the <a href="http://sunshinephp.com/register" title="Speaker: SunshinePHP Registration">Registration page</a>.
    </p>
    
    <div style="padding-left: 30px;">
<php print_r($sessions); ?>
        <!--<div id="talk_tag" style="text-align: justify;">
            <hr />
        
            <h2>talk_title</h2>
        
            <a href="/speakers#speaker_tag" title="Speaker: speaker_name">speaker_name</a>
            <div class="tag large session">Session</div>&nbsp;<div class="tag large beginner">Beg</div>&nbsp;<div class="tag large development">Development</div>

            <br /><br />

            talk_abstract<br /><br />
        </div>-->


        <hr />
    </div>
</div>