<div class="page-header">
    <h1>Tutorials</h1>
</div>
<div id="block-mine">
    <p style="text-align: justify;">
        Below is a full listing of the 3-hour in-depth SunshinePHP tutorials to be presented on February 4th the day prior to the official conference.<br /><br />

        NOTE: In order to attend these 3-hour in-depth tutorials an additional ticket for the tutorial day must be purchased from the <a href="http://sunshinephp.com/register" title="Speaker: SunshinePHP Registration">Registration page</a>.
    </p>

    <div style="padding-left: 30px;">
        <div id="tuturl" style="text-align: justify;">
            <hr />

            <h2>tutname</h2>

            <a href="/speakers#speakerurl" title="Speaker: speakername">speakername</a><br /><br />
    
            tutdescription<br /><br />
        </div>
    
    </div>
    <hr />
</div>